### ISSUE TITLE
ウィンドウ吸着が自動的に表示されます

### ISSUE THREAD

**Issue by Danjuanlab** [sorayuki/obs-multi-rtmp#1]
こんにちは、中国のゲームアンカーです。昨日このプラグインを発見しました。 本当に便利です！ よろしくお願いします！ しかし、このウィンドウの吸着フロートは、OBSを再び開くたびに最後のサイズを維持しないことがわかりましたが、この問題を解決するために、時々フロートアウトします。
さらに、私はあなたがこのソフトウェアをローカライズして、あなたが書いたソフトウェアをより楽しむことができるように、喜んでお手伝いします！ 私はnginxを使用してマルチプラットフォームのプッシュストリーミングを行っています。プラグインはnginxよりもはるかに便利です！ !! !!

Hello, I am a Chinese streamer, and I discovered this plugin the day before yesterday! It is really useful! thank you so much! But I found that the adsorption float of this dock does not keep the last size every time I reopen the OBS, but it floats out sometimes, hoping to solve this problem.
In addition, I am very willing to help you localize this software so that you can more enjoy the software you develop! I have been usidng nginx to do multi-platform push streaming. Your plugin is much more convenient than nginx! !! !!

![21](https://user-images.githubusercontent.com/42509669/77845661-380b4900-71e3-11ea-9f2f-71e579396430.png)
![22](https://user-images.githubusercontent.com/42509669/77845664-3a6da300-71e3-11ea-874e-eaf1a15e6623.png)

**Comment by Danjuanlab** [comment]
不是，你是中国人？一脸问号

**Comment by sorayuki** [comment]
是啊是啊，所以是不是直接qq说快一点。
obs这api，提供的加浮动窗的方法加上去保存不了位置；不用它api用自己的办法加（现在是这样），又没法显示和关闭。
不知道怎么调教。现在就干脆假设一定是吸在主窗口并且是显示的状态。吸在什么方向我是自己存的，窗口拉多大倒是obs存的

**Comment by Danjuanlab** [comment]
加QQ聊聊，372152212。因为我只开发过obs的python脚本，没用C++写过插件。我的思路是是不是可以参考下官方的自定义浏览器dock的源码？因为这个dock也是用户自定义后加的，但是它的位置和吸附都是能够保存下来的。
https://github.com/obsproject/obs-studio/search?q=ExtraBrowsers&unscoped_q=ExtraBrowsers

**Comment by shugen002** [comment]
这个dock的开关状态好像也是个问题，我把这个dock关闭了之后，下一次打开依然会自己呆在那。

**Comment by sorayuki** [comment]
> 这个dock的开关状态好像也是个问题，我把这个dock关闭了之后，下一次打开依然会自己呆在那。

咦还有问题吗，我记得最后一次测试我这边已经好了。现在忙死，等下班了看看

**Comment by shugen002** [comment]
补充一下，如果是点菜单栏查看菜单的停靠部件中关闭多路推流面板是不记录状态的

**Comment by sorayuki** [comment]
> 补充一下，如果是点菜单栏查看菜单的停靠部件中关闭多路推流面板是不记录状态的

原来是菜单那边操作的。修好啦

**Comment by Rongrock** [comment]
谢谢 提供这么好的插件
