### ISSUE TITLE
Request: FPS adjustment option

### ISSUE THREAD

**Issue by sneakyjoeru** [sorayuki/obs-multi-rtmp#11]
I've had my first stream with this extension yesterday, and it looks like the stream was done in 17 FPS when I selected nvenc (tried both old and new).
My main stream and record are done with 50 FPS.
I was trying to stream at 1440p. while main output is 1080p50, and recording is done with new nvenc at 1440p50

**Comment by sneakyjoeru** [comment]
![image](https://user-images.githubusercontent.com/54816725/82211355-67078680-9919-11ea-9f5f-c8b7a3e3a8ee.png)

**Comment by sorayuki** [comment]
There is no framerate limitation or adjustment logic in code.
I guess it's caused by overload of gpu or memory bandwidth.
If three way output has same resolution and bitrate, I recommend keep it "get from obs" and adjust resolution and bitrate in obs's setting dialog.
