### ISSUE TITLE
Virus detected when Im trying to download

### ISSUE THREAD

**Issue by pielol02** [sorayuki/obs-multi-rtmp#114]
I use Windows 10 32bit and Google Chrome as browser. When I download the "obs-multi-rtmp.zip" it kept cancel the download and shows Failed - Virus detected." Is there way to download this file without problem? Or is there setting that I need to change to download this file? Thank you.

**Comment by Lincolnhsp** [comment]
@pielol02 , don´t know if you solved the problem, but using Chrome version 99.0.4844.84 , and downloading directly from the assets page here, there wasn´t any trouble (check the bottom bar).

Source: https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.8

Almost sure it was a false positive.... tested downloading the ZIP and EXE packs.

![MRTMP - Download](https://user-images.githubusercontent.com/53958839/160726098-cfbb8295-3a5f-4025-9cc7-6b34426928ca.jpg)
