### ISSUE TITLE
关于一些小建议

### ISSUE THREAD

**Issue by lie5860** [sorayuki/obs-multi-rtmp#118]
大佬能在顶部加一个全部开始和全部停止吗。
还有现在推流列表存储在哪里呢。我可以通过对一个文件的写入来配置推流列表吗？

**Comment by sorayuki** [comment]
> 大佬能在顶部加一个全部开始和全部停止吗。
> 还有现在推流列表存储在哪里呢。我可以通过对一个文件的写入来配置推流列表吗？

C:\Users\[用户名]\AppData\Roaming\obs-studio\basic\profiles\[OBS的Profile名]\basic.ini
section是obs-multi-rtmp
key是json
保存的是经过base64编码的json字符串

**Comment by lie5860** [comment]
> > 大佬能在顶部加一个全部开始和全部停止吗。
> > 还有现在推流列表存储在哪里呢。我可以通过对一个文件的写入来配置推流列表吗？
> 
> C:\Users[用户名]\AppData\Roaming\obs-studio\basic\profiles[OBS的Profile名]\basic.ini
> section是obs-multi-rtmp
> key是json
> 保存的是经过base64编码的json字符串

好的 感谢大佬

**Comment by archer9812** [comment]
找到了ini里的json=后面部分，但是经过常规的base64解码出来的是一对乱码，不知道大佬用的什么办法还原这个base64串
