### ISSUE TITLE
Need Server Authentication

### ISSUE THREAD

**Issue by stormyjw** [sorayuki/obs-multi-rtmp#12]
Thank you for creating this plugin! I use Stream Monkey and their servers require an authentication username and password.  I don't see that as an option on your plugin
![obs-streamsettings](https://user-images.githubusercontent.com/42947634/82235741-5e4e8a80-98f0-11ea-89b8-e709ab57027f.jpg)

**Comment by sorayuki** [comment]
Hello, I have no account to any streaming service provider which need authentication.
But would you still like to have a try this version?
https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.4

**Comment by stormyjw** [comment]
I just tried it, but I get "Error.ServerHandshake"  when I try to connect.

**Comment by stormyjw** [comment]
And here is a link to the required OBS settings for my streaming provider.
https://support.streammonkey.com/en/articles/1136916-obs-open-broadcasting-software-encoder-setup

**Comment by sorayuki** [comment]
sorry it's my fault that passed "rtmp server" and "rtmp key" to "username" and "password".
please re-download and have another try.
If it still doesn't work, I may have a look tomorrow (it's 1:00am here)
by the way the translation seems broken. doesn't it fallback to English?

**Comment by stormyjw** [comment]
It shows I am now connected!
Just getting it working my my provider. Thank you!
This is fantastic!
