### ISSUE TITLE
Changes not saved when modifying

### ISSUE THREAD

**Issue by chticer** [sorayuki/obs-multi-rtmp#126]
Any changes I make after clicking the "Modify" button is not retained after clicking the "OK" button when putting in the information. I can add and delete any targets, just not save targets. I see in other issues and posts where this occurs when closing and opening OBS again but this happens while I have OBS opened.

**Comment by chticer** [comment]
The version I am using is 0.2.7. I can confirm that this issue does not exist in 0.2.6.1.

**Comment by sorayuki** [comment]
I will compare code and fix later today.
The release is now deleted.

**Comment by sorayuki** [comment]
fixed in 0.2.7.1
