### ISSUE TITLE
New Target not saving data

### ISSUE THREAD

**Issue by mikeysouthwell** [sorayuki/obs-multi-rtmp#127]
Hi Sorayuki,

This is still an issue on the latest version of OBS and OSB-Mutli RTMP on Windows 10.

The docking is working fine, but when you create a new target the data isn't saved.

I have tried multiple combinations of choosing modify and changing the name only or the RTMP server or key values only and none of these work. The New Target persists between sessions, but there is no data saved in it so it's useless.

Can you please resolve this?

I'm happy to provide further info if required.

I had to install the portable version of the plugin as the latest version of the installer gives a virus warning from Microsoft Windows and can't be installed.

**Comment by sorayuki** [comment]
Hi, is it the bug existing in 0.2.7?
it should has been fixed in 0.2.7.1. would you try this version?

**Comment by mikeysouthwell** [comment]
This is now fixed in the 0.2.7.1 release.

Thank you! :)
