### ISSUE TITLE
Virus??

### ISSUE THREAD

**Issue by Bluemethyst** [sorayuki/obs-multi-rtmp#138]
I was installing the windows version through google chrome and it would not let me install it because it thought it was a virus. Can you please fix this because your plugin is amazing <3

**Comment by iandouglas** [comment]
Is it actually finding a virus, or is it just warning you that the executable is unsigned by the author or something?

(I'm about to go try this on my own windows machine, but thought I'd ask here.)

**Comment by iandouglas** [comment]
I uploaded this to an online scanner and several other scanners detect malware in it as well
https://www.virustotal.com/gui/file/2ef835cf9074575066c3eacf5538182a83aa2a6fd9caf034a4f33dfc467d4024

**Comment by iandouglas** [comment]
FWIW, the last 0.2.7 build doesn't flag as having malware at all, just the latest 0.2.8 build.

**Comment by hackerb9** [comment]
Weird that there's been no response and this plugin has been flagged as a virus for quite a while. Thanks @iandouglas for mentioning that 0.2.7 doesn't trigger the virus warning; I'm going to suggest that my friend install that until this gets sorted out.

**Comment by hackerb9** [comment]
I don't know why, but 0.3.0.1 still isn't getting a completely clean bill of health. Lumu Antivirus is marking it as malicious, but isn't more specific than that.

https://www.virustotal.com/gui/url/a696fb71e68571db5006d747bb31cf211099b730eae3db5dc91ab1a74ae2d0fe

https://www.virustotal.com/gui/url/8cbbf21e3c2f3d0b01fe7f2aefdb2c9d4d78ea06f7c8f1c37e547a899668cf6c?nocache=1
