### ISSUE TITLE
[BUG]因为插件断流（或者其他）导致虎牙直播超过10分钟自动关闭直播间

### ISSUE THREAD

**Issue by niu164** [sorayuki/obs-multi-rtmp#139]
如题，播着播着发现虎牙直播间超时没推流关闭了，但是插件还显示的正在直播，并且FPS波动，但实际直播间已经超过时长限制，关播了，有时候播30分钟推流就断了，有时候两个小时都不断，请问插件有日志吗，在哪我可以补充

**Comment by sorayuki** [comment]
插件推流逻辑和行为与OBS一致。
日志和OBS主程序一起的。如果还有帧率显示，那么服务器应该和你没有断开连接的。
如果虎牙那边转流出了问题，应该反馈给虎牙，可以带上OBS的日志。

**Comment by niu164** [comment]
> 
[2021-12-02 23-42-00.txt](https://github.com/sorayuki/obs-multi-rtmp/files/7646384/2021-12-02.23-42-00.txt)
这是日志，虽然有帧率显示，但是我点关播重新开播，就会提示重新连接服务器，虎牙一直说让我用PC客户端直播，麻了
我发现甚至有时候不到10分钟就掉直播，最低5分钟掉一次

**Comment by sorayuki** [comment]
发给我没用……你要找虎牙啊。我又看不到虎牙那边的后台记录能不能和日志对上

**Comment by niu164** [comment]
> 

好吧，主要是直接发虎牙感觉会被直接查多平台直播

**Comment by sorayuki** [comment]
如果同时有多路在推，日志里面确实会有多开的记录。就算只有一路在推，这个插件创建的推流实例的名字也有明显的特征。
另外使用插件的时候还是要遵守具体平台的要求

**Comment by niu164** [comment]
> 如果同时有多路在推，日志里面确实会有多开的记录。就算只有一路在推，这个插件创建的推流实例的名字也有明显的特征。 另外使用插件的时候还是要遵守具体平台的要求

好的，我准备卸载插件，只推一路，看看断不断，断了再发日志给虎牙
