### ISSUE TITLE
rotate just one output by 90 degrees,

### ISSUE THREAD

**Issue by Eonassis** [sorayuki/obs-multi-rtmp#14]
rotate just one output by 90 degrees, there are platforms like instagram, that the video should be rotated, so that it stays in full screen.
![instagram-live-video](https://user-images.githubusercontent.com/22618048/82243363-d7aca400-9915-11ea-9b25-96ef2e3340b0.jpg)
![maxresdefault](https://user-images.githubusercontent.com/22618048/82243464-0cb8f680-9916-11ea-9a95-047a61d482bd.jpg)

**Comment by reustaquiojr** [comment]
Você poderia ao menos se retratar com o desenvolvedor e com a comunidade...

https://pascombrasil.org.br/agente-da-pascom-desenvolve-plugin-para-transmissao-ao-vivo/

**Comment by Eonassis** [comment]
> Você poderia ao menos se retratar com o desenvolvedor e com a comunidade...
> 
> https://pascombrasil.org.br/agente-da-pascom-desenvolve-plugin-para-transmissao-ao-vivo/

ok send report now

**Comment by Eonassis** [comment]
> Você poderia ao menos se retratar com o desenvolvedor e com a comunidade...
> 
> https://pascombrasil.org.br/agente-da-pascom-desenvolve-plugin-para-transmissao-ao-vivo/

**Comment by Eonassis** [comment]
> Você poderia ao menos se retratar com o desenvolvedor e com a comunidade...
> 
> https://pascombrasil.org.br/agente-da-pascom-desenvolve-plugin-para-transmissao-ao-vivo/
@reustaquiojr 
gostaria que me respeitasse, nao estou aqui pra roubar código de alguém, o meu instalador instala alem do plugin dele mais 3 programas que criei se você nao sabe. e com a imagem abaixo o mesmo e citado no README e no momento da instalação do mesmo.

sei que na internet tem pessoas que só pensam em fazer o mal pra outras, 
porque vc nao o fez antes de min e traduziu o mesmo?
porque nao criou ou tentou melhorar ele?
isso e comunidade, e nao apenas criticar. 
assim como o desenvolvedor, meu amigo, nao cobro, dou suporte gratuito, jha ajudei mais de 200 paroquias com suporte inclusive a noite e fins de semana, me poupe,

Desta forma nao chegaras tao longe.

se vc observar existe um fork do projeto de sorayuki

10 O ladrão vem somente para roubar, matar e destruir; eu vim para que tenham vida e a tenham em abundância. Jo 10.10

segue o print do meu software ele existe este foi eu que fis mesmo.

![image](https://user-images.githubusercontent.com/22618048/82250597-24967780-9922-11ea-8d9a-d580b8677b6a.png)

segue o print da instalação mostrando a referencia 

plugin created by sorayuki, original name obs-multi-rtmp, repository https://github.com/sorayuki/obs-multi-rtmp/, I just created the automatic liturgy generator for OBS, translate it into portuguese and created an installer for even, doubts and updates look for the developer.


plugin criado por sorayuki, nome original obs-multi-rtmp, repositorio https://github.com/sorayuki/obs-multi-rtmp/, eu apenas criei o gerador automatico de liturgia para OBS, traduzir para portugues e criei um instalador do mesmo, duvidas e atualizacoes procure o desenvolvedor.

plugin creado por sorayuki, nombre original obs-multi-rtmp, repositorio https://github.com/sorayuki/obs-multi-rtmp/, acabo de crear el generador de liturgia automático para OBS, traducirlo al portugués y crear un instalador para incluso, dudas y actualizaciones buscan el desarrollador.


由sorayuki創建的插件，原始名稱為obs-multi-rtmp，存儲庫為https://github.com/sorayuki/obs-multi-rtmp/，我剛剛為OBS創建了自動禮儀生成器，將其翻譯為葡萄牙語，並創建了一個安裝程序 甚至，疑問和更新也會尋找開發人員。


![aaaa](https://user-images.githubusercontent.com/22618048/82250530-016bc800-9922-11ea-8adf-e15da448404f.png)

@reustaquiojr
I would like you to respect me, I'm not here to steal someone's code, my installer installs in addition to his plugin 3 more programs that I created if you don't know. and with the image below the same and quoted in the README and at the time of installation.

I know that on the internet there are people who only think about doing harm to others,
why didn't you do it before me and translated the same?
why didn't you create or try to improve it?
that is community, not just criticism.
as well as the developer, my friend, I don’t charge, I give free support, I’ve helped over 200 parishes with support including evenings and weekends, save me,


if you observe there is a fork of sorayuki's project

follow the print of my software it exists this was me that fis.
