### ISSUE TITLE
OBS异常断流重连，求解决

### ISSUE THREAD

**Issue by niu164** [sorayuki/obs-multi-rtmp#144]
![image](https://user-images.githubusercontent.com/76257039/148359729-8230327e-7239-4233-9282-5b31e7f08cb7.png)
如图，详细的日志在这
[2022-01-06 13-48-52.txt](https://github.com/sorayuki/obs-multi-rtmp/files/7820754/2022-01-06.13-48-52.txt)

单独使用官方插件的斗鱼没断流，但是填在插件上的虎牙推流提示重连，而且连了好几次才行
600M宽带，上传200m，而且我码率设置较低

**Comment by sorayuki** [comment]
虎牙服务器主动断的你。
检查几个地方
1 推流码是不是填对，有没有类似房间开播的地方没开
2 是不是OBS主程序和插件推到同一个地方了，或者插件创建了多个推到同一个地方的目标
3 有没有类似码率超出虎牙限制之类的设定
4 试一下OBS主程序推虎牙是不是正常

**Comment by niu164** [comment]
> 虎牙服务器主动断的你。 检查几个地方 1 推流码是不是填对，有没有类似房间开播的地方没开 2 是不是OBS主程序和插件推到同一个地方了，或者插件创建了多个推到同一个地方的目标 3 有没有类似码率超出虎牙限制之类的设定 4 试一下OBS主程序推虎牙是不是正常

1 不点开播，推不出去的会提示重新链接服务器
2 我是斗鱼用官方obs插件，虎牙用多路推流插件，设置哪里的推流地址为空
3 码率2500-4000
4 明天尝试一下主程序推虎牙
今天重装了obs和插件，虽然目前还没提示断连，但是日志中发现了一样的错误代码，明天试试
![image](https://user-images.githubusercontent.com/76257039/148412244-451751e5-ad01-4ea7-a17f-b85881dc6556.png)

**Comment by niu164** [comment]
> 虎牙服务器主动断的你。 检查几个地方 1 推流码是不是填对，有没有类似房间开播的地方没开 2 是不是OBS主程序和插件推到同一个地方了，或者插件创建了多个推到同一个地方的目标 3 有没有类似码率超出虎牙限制之类的设定 4 试一下OBS主程序推虎牙是不是正常

我发现出现那个代码的原因是虎牙没点开播，但是昨天我是已经开播了已经播了一会了，突然出现obs正在重连，我昨天重装了OBS现在用主程序测试下稳定性

**Comment by niu164** [comment]
> 虎牙服务器主动断的你。 检查几个地方 1 推流码是不是填对，有没有类似房间开播的地方没开 2 是不是OBS主程序和插件推到同一个地方了，或者插件创建了多个推到同一个地方的目标 3 有没有类似码率超出虎牙限制之类的设定 4 试一下OBS主程序推虎牙是不是正常

![image](https://user-images.githubusercontent.com/76257039/148634412-462404a0-5003-4a57-9f5b-59e92bc319a5.png)
目前正常了虽然日志文件还有错误代码，但是obs没提示重连了

**Comment by sorayuki** [comment]
> > 虎牙服务器主动断的你。 检查几个地方 1 推流码是不是填对，有没有类似房间开播的地方没开 2 是不是OBS主程序和插件推到同一个地方了，或者插件创建了多个推到同一个地方的目标 3 有没有类似码率超出虎牙限制之类的设定 4 试一下OBS主程序推虎牙是不是正常
> 
> ![image](https://user-images.githubusercontent.com/76257039/148634412-462404a0-5003-4a57-9f5b-59e92bc319a5.png) 目前正常了虽然日志文件还有错误代码，但是obs没提示重连了

看这个日志……你检查一下你网络的上行带宽是不是扛得住播多个平台

**Comment by niu164** [comment]
> 

![image](https://user-images.githubusercontent.com/76257039/148634561-a04b65b8-31ff-4b78-bf96-5082eccea79c.png)

182m上行带宽，应该是够的吧，我在学校用100m的都能播，我同时推两个平台

**Comment by sorayuki** [comment]
产生50000多个包才发出去接近17000，一半以上丢了的。
这个测速可能连的是移动自己网络里的节点，可以尝试换一个一线城市电信或者联通的再测一下。
另外如果码率调成2倍不用插件直接只推虎牙一个平台，最后日志还是这种结果，那基本能确定就是网的问题。

**Comment by niu164** [comment]
> 产生50000多个包才发出去接近17000，一半以上丢了的。 这个测速可能连的是移动自己网络里的节点，可以尝试换一个一线城市电信或者联通的再测一下。 另外如果码率调成2倍不用插件直接只推虎牙一个平台，最后日志还是这种结果，那基本能确定就是网的问题。

补充一下，我今天刚开始的时候不知道为啥obs下面颜色的红色的，显示严重丢帧，我断开重新推流好了，之前没出现过这种情况

**Comment by lulinfeng** [comment]
我的才30M上传带宽，同时推3家没问题，其中也包括虎牙。

**Comment by niu164** [comment]
> 虎牙服务器主动断的你。 检查几个地方 1 推流码是不是填对，有没有类似房间开播的地方没开 2 是不是OBS主程序和插件推到同一个地方了，或者插件创建了多个推到同一个地方的目标 3 有没有类似码率超出虎牙限制之类的设定 4 试一下OBS主程序推虎牙是不是正常
[2022-01-13 23-40-04.txt](https://github.com/sorayuki/obs-multi-rtmp/files/7864605/2022-01-13.23-40-04.txt)
同样的问题有出现了，这次还有了新的错误代码
![image](https://user-images.githubusercontent.com/76257039/149376624-6af02fee-6161-4b4a-8ed1-a357f2308072.png)

**Comment by linkeyd** [comment]
我也发生过这种情况，应该是主动断你的。
你用虎牙直播工具第三方推流过去转发rtmp流一次后就不会主动断流了。
缺点就是网页端直播自动关闭失效，就算没推流超过15分钟也无法自动关闭，必须手动关闭，给写个定时关闭任务页面直播任务。
