### ISSUE TITLE
用了之后无法采集到音频了

### ISSUE THREAD

**Issue by ShaoLongFei** [sorayuki/obs-multi-rtmp#154]
使用安装程序也无法卸载

**Comment by sorayuki** [comment]
有具体吗？
卸载的话，运行安装程序应该会提示是否卸载。或者没有的话，可以看看安装程序上面显示的安装路径是哪里，跟着找到那个地方删掉文件就好了。安装过程中不会写注册表或者添加快捷方式，所以可以删干净的
一般在 C:\ProgramData\obs-studio 那个里面

**Comment by ShaoLongFei** [comment]
问题已解决，我把整个 OBS 卸了重装了
