### ISSUE TITLE
Set live title

### ISSUE THREAD

**Issue by Mte90** [sorayuki/obs-multi-rtmp#156]
I see that on youtube and twitch the title is generated automatically and there is no way to change it before the live streaming.

**Comment by sorayuki** [comment]
Does it go wrong when edit live settings?
It should be able to modified in edit dialog.

**Comment by Mte90** [comment]
What edit dialog? The modify button open a window for the streaming settings doesn't have field for that.

**Comment by sorayuki** [comment]
<img width="926" alt="edit-title" src="https://user-images.githubusercontent.com/16860691/159268211-13e5ce19-bb09-43bb-897e-d9478f085460.png">
is the input box there?

**Comment by sorayuki** [comment]
It doesn't affect the live service.
It's just for you to remember that where the item does streaming to.

**Comment by Mte90** [comment]
Ok so there was a confusion, I was talking about set the Live Title with OBS for both the services inside OBS.
