### ISSUE TITLE
streaming status, and time to live, notify

### ISSUE THREAD

**Issue by Eonassis** [sorayuki/obs-multi-rtmp#16]
visual broadcast status and live time, individually

![visual](https://user-images.githubusercontent.com/22618048/82245627-b6e64d80-9919-11ea-9710-a9bf3e70d985.png)

alert and notification in case of link failure or other error during transmission

![image](https://user-images.githubusercontent.com/22618048/82246822-c4043c00-991b-11ea-9cd2-e55e11385192.png)

**Comment by RockNRollGeek** [comment]
+1, this would be a nice feature to have.

**Comment by RockNRollGeek** [comment]
Was this closed because it's being implemented and is in an upcoming release? Or?

**Comment by Eonassis** [comment]
@sorayuki  close in yesterday
