### ISSUE TITLE
mac 版如何卸载？

### ISSUE THREAD

**Issue by sinkcup** [sorayuki/obs-multi-rtmp#164]
安装了 mac 版 pkg 格式的本插件，发现经常断流，然后卸载插件、卸载 obs、重启电脑、安装 obs，发现插件还在……

我使用的卸载命令： 

```
pkgutil --pkgs | grep -i obs

pkgutil --files com.sorayuki.obs-multi-rtmp

sudo pkgutil  --forget   com.sorayuki.obs-multi-rtmp
```

**Comment by celleo** [comment]
> 安装了 mac 版 pkg 格式的本插件，发现经常断流，然后卸载插件、卸载 obs、重启电脑、安装 obs，发现插件还在……
> 
> 我使用的卸载命令：
> 
> ```
> pkgutil --pkgs | grep -i obs
> 
> pkgutil --files com.sorayuki.obs-multi-rtmp
> 
> sudo pkgutil  --forget   com.sorayuki.obs-multi-rtmp
> ```

我也是今天刚安装这个插件，但我觉得你可以先找下OBS Studio的插件路径：Library/Application Support/obs-studio/plugins。

**Comment by sinkcup** [comment]
感谢 @celleo 

```shell
ls /Library/Application\ Support/obs-studio/plugins
obs-gstreamer  obs-multi-rtmp
```

**Comment by sorayuki** [comment]
原来是这样……对macos一窍不通的我都不知道pkg本质上是什么样的东西、macapp的软件结构啥的orz

**Comment by warlock-lv** [comment]
> 安装了 mac 版 pkg 格式的本插件，发现经常断流，然后卸载插件、卸载 obs、重启电脑、安装 obs，发现插件还在……
> 
> 我使用的卸载命令：
> 
> ```
> pkgutil --pkgs | grep -i obs
> 
> pkgutil --files com.sorayuki.obs-multi-rtmp
> 
> sudo pkgutil  --forget   com.sorayuki.obs-multi-rtmp
> ```

我用  pkgutil --pkgs | grep -I obs 这个什么也没有唉，怎么办呢？  M1 电脑。
