### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by patrickfeeney03** [sorayuki/obs-multi-rtmp#177]
I've even tried reinstalling OBS but the plugins is still there. How do I get rid of it?
Thanks

**Comment by Romvnly-Gaming** [comment]
Once you're a part of the cult, there is no leaving mate. The only thing you can do now is to uninstall Windows. After doing so, bash your hard drive and then you'll be free of this program.

**Comment by sorayuki** [comment]
re-run installer or remove C:\ProgramData\obs-studio\plugins\obs-multi-rtmp folder

**Comment by hkenshin89** [comment]
That obs-multi-rtmp folder doesn't exist!

**Comment by SlavenIvanov** [comment]
How do you uninstall the software on OSX?

**Comment by JavierCane** [comment]
is there any way to uninstall it manually?

Thanks!

**Comment by sorayuki** [comment]
goto c:\programdata\obs-studio to remove the obs-multi-rtmp
________________________________
