### ISSUE TITLE
Support for OBS Studio Ver28

### ISSUE THREAD

**Issue by sumside** [sorayuki/obs-multi-rtmp#180]
-Japanese -

こんにちわ。このプラグインはすごく便利で愛用しています。
製作してくれてありがとう。

ところで、OBS Studioの次のバージョン(ver28)ではQt5.15からQt6.3ベースに切り替わるため、いろんなプラグインが動かなくなる見込みです。

このプラグインは次のバージョンのOBS Studioに対応する予定はありますか？
対応していただけることを願っています。

- automatic translation -

Hello. This plugin is very useful and I love it.
Thanks for producing it.

By the way, the next version of OBS Studio (ver 28) is expected to switch from Qt5.15 to Qt6.3 based, so various plugins are not expected to work.

Is there any plan to support this plugin in the next version of OBS Studio?
We hope it will be supported.

**Comment by sorayuki** [comment]
今日は遊園地に行くから後でしようと思う。
教えてくれてありがとう

**Comment by sumside** [comment]
Thanks for your reply.
Take your time and enjoy👍

**Comment by MrSataana** [comment]
Can not wait for the update! Really missing this :)

**Comment by sorayuki** [comment]
対応しました。
