### ISSUE TITLE
Plugin not showing up in OBS 27.2.4 on Windows

### ISSUE THREAD

**Issue by kentnek** [sorayuki/obs-multi-rtmp#185]
Hi, after installing the plugin to "C:\ProgramData\obs-studio\plugins\obs-multi-rtmp" and restarting OBS, I still don't see the plugin UI. Is there anything extra I need to do? 

Thanks!

**Comment by sorayuki** [comment]
Hi, which version has you downloaded?
The latest one is for OBS 28 only. The previous one is for OBS 27.

**Comment by kentnek** [comment]
oh that explains it. Thank you!
