### ISSUE TITLE
Problem with OBS 28

### ISSUE THREAD

**Issue by Mikace** [sorayuki/obs-multi-rtmp#188]
I love your plugin, are you planning on updating it for OBS 28??? And also for M1 Macs??? I'm planning on buying one for my videos.

**Comment by Mikace** [comment]
Thanks a lot!!!!

**Comment by sorayuki** [comment]
For OBS 28 Beta macOS, refer this link https://github.com/kilinbox/obs-multi-rtmp/releases/tag/0.2.8.1

**Comment by hardlevel** [comment]
there's something for windows?

**Comment by sorayuki** [comment]
> there's something for windows?

You mean this?
https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.8.1-OBS28

**Comment by hardlevel** [comment]
> > there's something for windows?
> 
> You mean this? https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.8.1-OBS28

hi thanks! i tested but didn't worked on obs 28.1 it still saying that the plugin isn't compatible

**Comment by sorayuki** [comment]
> > > there's something for windows?
> > 
> > 
> > You mean this? https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.8.1-OBS28
> 
> hi thanks! i tested but didn't worked on obs 28.1 it still saying that the plugin isn't compatible

try unstall the old one.
Delete ```C:\ProgramData\obs-studio\plugins\obs-multi-rtmp``` if it exists.
Delete ```(where your obs installed)\obs-plugins\64bit\obs-multi-rtmp.dll``` and ```(where your obs installed)\data\obs-plugins``` if it exists

Then install the new one
