### ISSUE TITLE
where are  obs-multi-rtmp plugin save config fine path for windows？

### ISSUE THREAD

**Issue by xiefei99** [sorayuki/obs-multi-rtmp#195]
i need help  ,help  me  help me。
windows的插件保存的推流配置文件存放在哪里？我应该如何通过配置文件修改批量修改已经保存的配置？

from, obs version 27.2 windows11

**Comment by sorayuki** [comment]
ini文件里面。
从代码可以看到是一个json字符串通过base64编码之后塞ini里了

**Comment by sorayuki** [comment]
0.4.0.0保存在单独的json文件里了
