### ISSUE TITLE
Missing encoder NVIDIA NVENC HEVC in option

### ISSUE THREAD

**Issue by DavSonCZE** [sorayuki/obs-multi-rtmp#204]
Hi,
I've been trying to figure out how to find NVIDIA NVENC HEVC in the encoder options. But still the darkness does not show up. Even switching platforms didn't help it doesn't show up in the options. 

Thank you in advance.

**Comment by sorayuki** [comment]
Hi, RTMP does not support HEVC.
________________________________
From: DavSonCZE ***@***.***>
Sent: Wednesday, September 28, 2022 10:30:58 PM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] Missing encoder NVIDIA NVENC HEVC in option (Issue #204)


Hi,
I've been trying to figure out how to find NVIDIA NVENC HEVC in the encoder options. But still the darkness does not show up. Even switching platforms didn't help it doesn't show up in the options.

Thank you in advance.

―
