### ISSUE TITLE
Malware detected on Windows10

### ISSUE THREAD

**Issue by d4vinder** [sorayuki/obs-multi-rtmp#205]
**FILE: OBS-MULTI-RTMP-SETUP.EXE** 

Malwarebytes
www.malwarebytes.com

-Log Details-
Scan Date: 30/09/2022
Scan Time: 12:33
Log File: c1f36020-40b3-11ed-a244-005056c00001.json

-Software Information-
Version: 4.5.12.204
Components Version: 1.0.1725
Update Package Version: 1.0.60523
Licence: Free

-System Information-
OS: Windows 10 (Build 19044.2006)
CPU: x64
File System: NTFS
User: *********

-Scan Summary-
Scan Type: Custom Scan
Scan Initiated By: Manual
Result: Completed
Objects Scanned: 1
Threats Detected: 1
Threats Quarantined: 0
Time Elapsed: 0 min, 22 sec

-Scan Options-
Memory: Disabled
Startup: Disabled
Filesystem: Enabled
Archives: Enabled
Rootkits: Disabled
Heuristics: Enabled
PUP: Detect
PUM: Detect

-Scan Details-
Process: 0
(No malicious items detected)

Module: 0
(No malicious items detected)

Registry Key: 0
(No malicious items detected)

Registry Value: 0
(No malicious items detected)

Registry Data: 0
(No malicious items detected)

Data Stream: 0
(No malicious items detected)

Folder: 0
(No malicious items detected)

File: 1
Malware.AI.4173832698, C:\USERS\*****\DOWNLOADS\OBS-MULTI-RTMP-SETUP.EXE, No Action By User, 1000000, -121134598, 1.0.60523, D8D084F498164B8CF8C7A1FA, dds, 01970438, A961FABDFAB392DBA1A19BE368F36F8B, 5125A1CC2FFAAA47C19CEF4AD9D3006FA9FE0C6F2B27BD55B41C43EB465B263A

Physical Sector: 0
(No malicious items detected)

WMI: 0
(No malicious items detected)

(end)

**Comment by Mythotical** [comment]
You can't use the EXE because of that. Just download the portable version zip file then extract the data and obs-plugin folders to your obs-studio directory and all done.
