### ISSUE TITLE
大佬能否开发一个美颜插件？

### ISSUE THREAD

**Issue by Shimmer2** [sorayuki/obs-multi-rtmp#209]
大佬你好！非常感谢你的obs多路推流插件！已经贫穷地打赏了一下大佬！非常感谢！！！不知道大佬能否开发一个mac版的美颜美白磨皮的插件？找遍了全网都没找到[大哭]

**Comment by Ryu945** [comment]
我不确定翻译人员是否给了我一个很好的翻译，但如果我理解正确的话，这应该有帮助。  这是该插件的Mac版本的位置。

https://github.com/sorayuki/obs-multi-rtmp/releases
 obs-multi-rtmp-portable.zip 

https://github.com/sorayuki/obs-multi-rtmp/releases/download/0.2.8.1-OBS28/obs-multi-rtmp-portable.zip

**Comment by sorayuki** [comment]
It says that "can you develop a filter plugin for face beautify which runs in macOS?" .
________________________________

**Comment by huanghe2015** [comment]
Please give the model of your Mac device to help. As you know, there are huge differences between x86 and ARM architechture.
请给出你的Mac型号。因为Mac有x86和ARM两种架构，差别巨大。
