### ISSUE TITLE
[SOLVED] Unable to compile Obs-Multi-Rtmp (0.2.8) LINUX

### ISSUE THREAD

**Issue by Querzion** [sorayuki/obs-multi-rtmp#219]
I'm not a very good Linux user. I tried to compile the plugin, but ended up with an error. I don't know how to fix it. 
Used this video; https://www.youtube.com/watch?v=DhexEgJjKNg

Since it's to difficult for programmers to include a if/else statement looking into the system and then installing the needed dependencies before compiling. This is the compile output anyways.

https://pastebin.com/A8GGzYk3

This is the system information, and OBS version.
![image](https://user-images.githubusercontent.com/39269026/201167262-cb07ea57-5c48-41ab-b7bd-c39acf65051c.png)
![image](https://user-images.githubusercontent.com/39269026/201167470-8864c0b3-8eb3-4560-8f30-a85282a17b6b.png)

**Comment by Querzion** [comment]
> Why are you being snarky about programmers? Especially when asking for help. @sorayuki has done this work for **free** and even if you have donated it's just to show appreciation, not to get features and support.

If I hadn't found that video I would never had been able to install the dependencies to compile the plugin. I think it shouldn't be so difficult for any person adding their code here, to do as everyone else seems to do, which is to point out which dependencies that are needed for their project to work. One other thing is to add a script that checks if the Linux distro is based on APT/Pacman or some other package manager, then install the dependencies automagically, which many other people do. 

So I'm not being snarky. I just don't get it why people doesn't add it in their code, and then rely on people to; especially in this case. FIND IT OUT FOR THEMSELVES. Does it state anywhere what I need in order to compile the code? Is that my fault? The readme is basically a hey donations please. I'm just stating something obvious. Sure I could perhaps be a bit 'nicer' about it, but the tone won't change the issue at hand. Only if it's going to be fixed a little bit faster. 

> CMake is literally checking for the library, that's the whole point of the error. That doesn't exist anymore (& linking should be done to the public API). It's not CMake's job to know what `LibObs` is and go download it from wherever it lives, there's not a central registry of these libraries.

I get that CMake couldn't find the library. It can't compile the plugin because information in that folder is needed. I'm not stupid, but I'm not capable of fixing the problem, since it's not my project that isn't working. 

This is the output, and not something that I added. It's the project itself that errol's out. 
![image](https://user-images.githubusercontent.com/39269026/201436923-a6151c93-955e-4809-b07a-bdb65dcf8b60.png)

**Comment by 3laws** [comment]
> Only if it's going to be fixed a little bit faster.

 You can't demand anything, even less with your attitude.

> If I hadn't found that video I would never had been able to install the dependencies to compile the plugin.

Dependencies are clear in the code.

>  One other thing is to add a script that checks if the Linux distro is based on APT/Pacman or some other package manager, then install the dependencies automagically, which many other people do.

You are free to open a pull request.

**Comment by Querzion** [comment]
> > Only if it's going to be fixed a little bit faster.
> 
> You can't demand anything, even less with your attitude.

I'm not demanding anything. I said that the only thing that a nicer tone would maybe(emphasis on MAYBE) end up with would be a faster fix. 


> > Unable to compile.
> 
> We're building, not compiling.

And? Semantics is taking you places; Is that it? Do I look like a programmer to you? 


> All that being said. Rename `libobsConfig.cmake` as indicated by #220 . Please don't be a jerk.

I saw that. You know what? It doesn't say where this file is supposed to be, looked through the folders hastily, and couldn't find it. I said I'm not a good Linux user, didn't I? I'm not being a jerk, if I were I would probably call people degrading stuff.

**Comment by Querzion** [comment]
Compile :to run (something, such as a program) through a [compiler](https://www.merriam-webster.com/dictionary/compiler)

So I looked it up, and it means to run. Isn't to build something... *./*=run a script to compile? I'm not building it, I'm running it, and the script builds it from set parameters. Am I wrong?

**Comment by 3laws** [comment]
>  It doesn't say where this file is supposed to be

Check `/usr/local/lib64/cmake/libobs/`

>Isn't to build something... ./=run a script to compile? 

No. You can learn more about it [here.](https://cmake.org/)

**Comment by Querzion** [comment]
> Isn't to build something... ./=run a script to compile?

./ is a run command, used to start compiling the script. That script has functions wherein it starts building the application with the help of the compiler. cmake is a compiler. g++ & gcc are compilers. I'm not building anything. I am using the compile command ./ 

Compile means to piece something together. The build is done by the compiler, with the help of the files, and the output is a built application ready to use. I can't see how I am building anything. Am I the compiler? Telling building the application from scratch? It's not the 80's where you would input data in order to start a game or application you know. 



> > It doesn't say where this file is supposed to be
> 
> Check `/usr/local/lib64/cmake/libobs/`

Thank you! <3

**Comment by Querzion** [comment]
> > It doesn't say where this file is supposed to be
> 
> Check `/usr/local/lib64/cmake/libobs/`
> 
> > Isn't to build something... ./=run a script to compile?
> 
> No. You can learn more about it [here.](https://cmake.org/)

I gave a thanks too hastily. I don't have such a folder. I have lib, but it's empty.

**Comment by Querzion** [comment]
I'll just skip trying to use the plugin for now. It has been working apparently, so it will probably start working again in the future.

**Comment by sorayuki** [comment]
I'm working on Windows platform and not familiar with linux or macos.
Building script for macos and linux are merged via pull request.

**Comment by Querzion** [comment]
Okay. ^^ 

Well one thing to know about Linux and always hold in mind is that it's case-sensitive. 

Hope that a Linux user down the road wants to tinker with the project. I'm not a programmer or know enough about the linux system, so I can't help.

**Comment by Querzion** [comment]
> Rename `libobsConfig.cmake` as indicated by #220 .

I chose to create a copy with the capital letters, since I have no Idea if something else also uses the file.

**Comment by Querzion** [comment]
> ![image](https://user-images.githubusercontent.com/39269026/201436923-a6151c93-955e-4809-b07a-bdb65dcf8b60.png)

![image](https://user-images.githubusercontent.com/39269026/201479391-8d22dbca-b607-44a6-93f1-f9429ea3fbbc.png)

**Comment by Querzion** [comment]
![image](https://user-images.githubusercontent.com/39269026/201479674-78d6fe91-f021-4619-8ad0-fe6eaba4ffe2.png)

I went into pch.h and commented obs-module.h, then this happened.

![image](https://user-images.githubusercontent.com/39269026/201479722-9696b245-1b63-49be-bd71-7595ce7cd15e.png)

so I ended up commenting that too. 

![image](https://user-images.githubusercontent.com/39269026/201479760-fccec618-7aa6-4a57-967a-44ac66fe736c.png)

Now I get this answer.

![image](https://user-images.githubusercontent.com/39269026/201479776-d2a9b259-0f1a-42e6-898a-d9c95c758948.png)

Commented out that too...

![image](https://user-images.githubusercontent.com/39269026/201479859-1d019853-f3ee-4a8b-b681-ead85ba49bd9.png)

I get it, the files are needed in order to get it working. So where are they located? Because they are sure as hell not in the source folder. 

![image](https://user-images.githubusercontent.com/39269026/201479905-1d38550e-fe0a-46e6-9ce0-77704cc34292.png)

Then I un-commented everything again.

**Comment by sorayuki** [comment]
You need download obs's source code tarball in which version you installed from github, and then extracting it into a folder named obs-src located in obs-multi-rtmp.
________________________________

**Comment by Querzion** [comment]
I installed OBS from "sudo flatpak install obs-studio", I started of installing it from within pamac & "sudo pacman -S obs-studio", but before all of this I installed an AUR version that I have been using for years in arch based systems, but apparently it wouldn't work with Manjaro, so that's why I had to uninstall OBS 2 times or three.  and then chose to install the flatpak and it worked. 

> You need download obs's source code tarball in which version you installed from github, and then extracting it into a folder named obs-src located in obs-multi-rtmp.

In the project folder? 
![image](https://user-images.githubusercontent.com/39269026/201481181-3d072d6d-d279-4459-a0fa-1475f9b63deb.png)

**Comment by sorayuki** [comment]
yes. but named the source code folder "obs-src".
compiling this project needs header files from obs's source code
________________________________

**Comment by Querzion** [comment]
Okay. As a standalone obs-multi-rtmp-master/obs-src or obs-multi-rtmp-master/src/obs-src. Just want to clarify the whole thing. 

I will re-download the project then.

**Comment by sorayuki** [comment]
obs-multi-rtmp-master/obs-src

to have a look at github action's build log for windows may helps.
Note that obs studio's source must match the installed obs-studio package.
________________________________

**Comment by Querzion** [comment]
I keep getting the same errors it's like the build has no idea where to look for the files that are included. I have tried multiple different ways now. 

![image](https://user-images.githubusercontent.com/39269026/201482584-c61cb664-4aff-4a65-98e5-12ff6947da7b.png)

obs-multi-rtmp-0.2.8.1-OBS28/src/libobs
obs-multi-rtmp-0.2.8.1-OBS28/src (dropping the libobs files in here for direct access to the files)
obs-multi-rtmp-0.2.8.1-OBS28/obs-src/OBS PROJECT
obs-multi-rtmp-0.2.8.1-OBS28/src/obs-src/OBS PROJECT

Changing the libobs to obs in CMakeLists.txt

Does not work. Changed src to obs-src... bad Idea, since that folder is specifically called for in row 81+ in the CMakeLists.txt.

Ended up going with 
![image](https://user-images.githubusercontent.com/39269026/201483778-93a9cdb3-4d0c-4a8b-be6b-e81c733f0975.png)
I however get the error with obs.h. No such file or folder, so I directed it directly to the file, and now I get no such file or folder.. I directed to the file in the obs-frontend-api.h, and it gives out a fatal error. It's really strange. I don't get it why it's like this. 

+ cmake --build build --config Release
[ 20%] Building CXX object CMakeFiles/obs-multi-rtmp.dir/cmake_pch.hxx.gch
In file included from /home/querzion/OBS/obs-multi-rtmp-master/src/pch.h:31,
                 from /home/querzion/OBS/obs-multi-rtmp-master/build/CMakeFiles/obs-multi-rtmp.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/querzion/OBS/obs-multi-rtmp-master/src/obs-src/UI/obs-frontend-api/obs-frontend-api.h:4:10: fatal error: ~/OBS/obs-multi-rtmp-master/src/obs-src/libobs/obs.h: No such file or directory
    4 | #include "~/OBS/obs-multi-rtmp-master/src/obs-src/libobs/obs.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-multi-rtmp.dir/build.make:77: CMakeFiles/obs-multi-rtmp.dir/cmake_pch.hxx.gch] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/obs-multi-rtmp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by sorayuki** [comment]
without modify the source code.

the folder is like this:
![QQ截图20221113002613](https://user-images.githubusercontent.com/16860691/201484152-3ed4e61e-90f8-4aa3-801f-ab64e3b37d20.png)

**Comment by Querzion** [comment]
I tested that. Without doing anything to the source code at all, can test do it again and show the output.
![image](https://user-images.githubusercontent.com/39269026/201486575-bb6323bb-9662-4fa1-8b43-2a2d58b42368.png)
![image](https://user-images.githubusercontent.com/39269026/201486598-4aafe5ae-52c6-4dac-9b49-bdf8dcf7d6ee.png)
![image](https://user-images.githubusercontent.com/39269026/201486637-bedfff48-d8c1-4773-8b2a-e08e140a17eb.png)
![image](https://user-images.githubusercontent.com/39269026/201486673-a9946e25-fa5d-477a-b88f-df452879f9b6.png)

**Comment by sorayuki** [comment]
I checked the cmake script. The build steps in Linux may call for many things which are unfriendly for non-programmer...
The OBS_SRC_DIR is set to obs-src folder by default i  Windows but not for linux. And I'm not sure if it works or not with a empty QTDIR
________________________________

**Comment by Viezovv** [comment]
Hello 

I follow this thread having the same errors as Querzion, but I managed to figure it out myself by trial and error.
I am using ubuntu studio 22.10 and obs 28.1.2

things i changed in files:

CmakeLists.txt  

1. set(LIB_OBS libobs) to set(LIB_OBS obs)
2. find_package(Lib0bs REQUIRED) to find_package(libobs REQUIRED)

then i have problem with included files, like obs-module.h, util/darray.h and etc.. ,so i edited pch.h
 
#include "obs-multi-rtmp.h"
#include "obs-src/libobs/obs-module.h"
#include "obs-src/UI/obs-frontend-api/obs-frontend-api.h"
#include "obs-src/libobs/util/config-file.h"

of course, I downloaded the obs master source and added it to the master rtmp, so I have separate src and obs-src folders

one more thing, you need to edit obs-frontend-ap-h, located in obs-src/UI/obs-frontend-api/

before
#include <obs.h>
#include <util/darray.h>

after
//#include <obs.h>
//#include <util/darray.h>

After all these procedures, I was able to compile the plugin, of course it works

;]

**Comment by Querzion** [comment]
NICE! I will test it myself. I was quite close then.

![image](https://user-images.githubusercontent.com/39269026/201495716-37f5c77f-0fd3-423b-aa40-499b69ee72d6.png)
![image](https://user-images.githubusercontent.com/39269026/201495723-3e2d477c-1b75-44db-bef7-f522236636e9.png)

And here's the output. 
![image](https://user-images.githubusercontent.com/39269026/201495768-ebdae8ab-4624-414e-9e5d-a28a417ab748.png)

Now all I have to do is add it to OBS. ^^

**Comment by Querzion** [comment]
@Viezovv Did you get the plugin to work? I have never used it before.

**Comment by Viezovv** [comment]
I'm testing it right now for 4 hours and it works twitch and bandlab together, earlier I had plugins in usr/share/obs/obs-plugins/
right now in /home/.config/obs-studio/plugins/

**Comment by Viezovv** [comment]
![Screenshot_20221113_001100](https://user-images.githubusercontent.com/118071929/201498138-f273516f-72a0-4204-a914-869e3a62f31a.png)

**Comment by Viezovv** [comment]
![Screenshot_20221113_002046](https://user-images.githubusercontent.com/118071929/201498413-a3a9a356-55b7-4e6f-9b49-3d31e3b260b6.png)

**Comment by Querzion** [comment]
I have the plugin in multiple places, and it's still not recognised. I will re-install my computer here shortly, and I will test everything afterwards.

**Comment by AntonioGomes42** [comment]
I made a new tutorial showing how to install it on a Flatpak OBS. I works for every single linux. Link : https://youtu.be/p4eoEoq438M. I hope it helps you!
