### ISSUE TITLE
Impossible to "Bind To IP" like OBS

### ISSUE THREAD

**Issue by instazedd** [sorayuki/obs-multi-rtmp#236]
Hello, thank you for this amzing plugin.

I use 2 internet connections on my PC at the same time. One of them has good download and bad upload, and the other one has good Upload but bad download.

So I use the good download connection as my main one for gaming and all other tasks, and only OBS uses the good upload one through the "Bind To IP" option in advanced settings.

But when i try streaming to multiple platforms, the plugin doen't follow the OBS IP, and uses the bad upload.

It would be great if you could add this to the settings, because for now, I can't use the plugin at all.

Thank you

**Comment by sorayuki** [comment]
supported since 0.5.0.0
