### ISSUE TITLE
Cannot change Obs streaming output resolution after installig it, and unable to uninstall with the .exe application

### ISSUE THREAD

**Issue by SUPA93** [sorayuki/obs-multi-rtmp#257]
I was trying to change my Obs output resolution to stream on YT. For twitch my output is 1664*936 and then when streaming on Yt it's scalling at 720p.
So i wanted to set up my Obs output at 1920*1080p. 
But Obs still saying ;" The video output is currently running. You should turn off all outputs before changing prameters.
But unfortunately all is down. I tried to remove this pluggin with the app , it's says DONE but the pluggin is still there. I tried manually but same issue. Cannot find it.
Also after checking my last stream on youtube, i saw that it wasn't working. But it was saying streaming. So something wrong also with this. 
Keep the great job !! This tool is awesome. If someone can help me to uninstall it thanks in advance

**Comment by sorayuki** [comment]
The installer put files in ```C:\ProgramData\obs-studio\plugins\obs-multi-rtmp``` folder.
Delete the folder manually if the installer fails to do it for you
