### ISSUE TITLE
Multiple output window not showing up anywhere..

### ISSUE THREAD

**Issue by tr1s** [sorayuki/obs-multi-rtmp#259]
I am following along in [this tutorial](https://youtu.be/RBXu1_jaes8) to use this plugin, and I didn't get very far.

I download the arm version of this plugin (I'm on a M1 Mac) and opened up OBS, but I don't see the window that I need to see. It shows up in the menu under "Docks" and is checked, but nothing shows up. It's not hiding behind any window either.

Is there something I'm missing here, or is this latest version broken?

![CleanShot 2023-03-22 at 12 11 23@2x](https://user-images.githubusercontent.com/19172250/226968839-443a8834-7555-4418-9443-2274a02cc09a.png)
![CleanShot 2023-03-22 at 12 10 52@2x](https://user-images.githubusercontent.com/19172250/226968848-aa5347ee-4a1a-466e-9eb8-9d3d2e61ac07.png)

**Comment by sorayuki** [comment]
Hi, there is rumor says it may show when you switch to studio mode, draging it somewhere and then switching back.
________________________________
From: Tristan Michael Lawrence ***@***.***>
Sent: Thursday, March 23, 2023 12:14:46 AM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] Multiple output window not showing up anywhere.. (Issue #259)


I am following along in this tutorial<https://youtu.be/RBXu1_jaes8> to use this plugin, and I didn't get very far.

I download the arm version of this plugin (I'm on a M1 Mac) and opened up OBS, but I don't see the window that I need to see. It shows up in the menu under "Docks" and is checked, but nothing shows up.

Is there something I'm missing here, or is this latest version broken?

[CleanShot 2023-03-22 at 12 11 ***@***.***<https://user-images.githubusercontent.com/19172250/226968839-443a8834-7555-4418-9443-2274a02cc09a.png>
[CleanShot 2023-03-22 at 12 10 ***@***.***<https://user-images.githubusercontent.com/19172250/226968848-aa5347ee-4a1a-466e-9eb8-9d3d2e61ac07.png>

―

**Comment by tr1s** [comment]
@sorayuki lol yup, that worked. I switched to Studio Mode and I saw a tiny box in the top left that I could drag out. Now it's here. Thank you!

**Comment by sorayuki** [comment]
Please download the matched version. The depending OBS version is written in release note.
________________________________
