### ISSUE TITLE
Audio encoder selection broken in OBS 29.1 beta

### ISSUE THREAD

**Issue by ImAciidz** [sorayuki/obs-multi-rtmp#262]
Presumably due to changes in OBS that allow you to now select an audio encoder in OBS 29.1, the only option available for audio encoder is "get from OBS". 
![image](https://user-images.githubusercontent.com/62849155/228587179-8b31f41e-efc3-4578-ba34-6075a8984589.png)
Plugin still functions after you start a normal OBS stream so that it can get the encoder.

**Comment by LinoYeen** [comment]
yeah I have this issue as well x-x

**Comment by dA-nebula** [comment]
same here. i had to downgrade to obs 29.0.2

**Comment by Peregons** [comment]
Found a solution: update multi-rtmp plugin. https://github.com/sorayuki/obs-multi-rtmp/releases/
