### ISSUE TITLE
b-frames

### ISSUE THREAD

**Issue by android6** [sorayuki/obs-multi-rtmp#28]
Some services require customization **bframes=0** 

Is it possible to add this option to the plugin?
And will it add load on the CPU?

**Comment by YammYcoding** [comment]
bump

**Comment by SanjeevKumarPandey** [comment]
Hi @sorayuki - we have also come across this requirement. Is it possible to include this as part of the target's config options? OBS already provides this option when you use the default stream settings in Advanced mode.

![image](https://user-images.githubusercontent.com/17326493/111252244-b18b8980-8636-11eb-84cd-7f3ff15d3272.png)

We're also looking to be able to set CBR, buffer size, and set tune=zerolatency for each target. Thanks!
