### ISSUE TITLE
"failed to create encoder object"

### ISSUE THREAD

**Issue by warcraftandy1** [sorayuki/obs-multi-rtmp#283]
I couldnt find anything about this error I get. I did successfully get my facebook to load up on the panel once, but after that it gave me this error. Platforms I tried Kick, Youtube, Twitch, and Personal Facebook (not yet Facebook page/groups,etc.). Any ideas how to resolve this would be amazing thanks!

**Comment by YarsGames** [comment]
Try version - obs-multi-rtmp 0.2.8.2 it work for me.

**Comment by KimKJDesigns** [comment]
Seems like v3 is forcing us to select a single source for all outgoing streams instead of rending the OBS preview.

**Comment by Joemaker2023** [comment]
I got this error too.
V0.3.0.1 on manjaro linux. how can I fix this issue?

**Comment by sorayuki** [comment]
Can you offer a copy of OBS log file?
________________________________

**Comment by sorayuki** [comment]
Be careful that the log file may contains rtmp stream key.
________________________________

**Comment by YarsGames** [comment]
This error does not create a record in the OBS log. The error usually occurs when the plugin scene coincides with the scene in OBS.

**Comment by YarsGames** [comment]
This error does not create a record in the OBS log. The error usually occurs when the plugin scene coincides with the scene in OBS.

**Comment by YarsGames** [comment]
For example, if you specify a different scene in the Scene section of the plugin, the error disappears. In older versions of the plugin, there was no Scene section and there was no error.

**Comment by sorayuki** [comment]
I'll check the case later.
________________________________

**Comment by CaDuSiMs** [comment]
Same problem here, had to revert back to version 0.2.8.2.

**Comment by CaDuSiMs** [comment]
To be clear and try to help you solve the problem SORAYUKI, this error only occurs for me when I try to use resolutions and bitrates different from the original (what OBS is transmitting).

**Comment by Joemaker2023** [comment]
I found the issue about this...Stream settings->scene->get from obs,got :failed to create encoder project.
but when I choose stream settings->scene-> other scene,everything is fine.
pls fix this issue. thanks
multir-tmp v0.3.0.1 obs v29.0.2 on manjaro linux.

**Comment by sorayuki** [comment]
Hello, the bug may have been fixed in 0.3.0.2.
Try latest release to see if it works.
