### ISSUE TITLE
failed to create encoder project again

### ISSUE THREAD

**Issue by Joemaker2023** [sorayuki/obs-multi-rtmp#286]
Sorry,maybe I didn't update new version successfully. and I will try again...I want to del this comments,but I can not.

**Comment by sorayuki** [comment]
I don't have a linux environment. 
The donate link in 0.3.0.2 now should be placed in the bottom of dock window.
Can you check the version again?

**Comment by Joemaker2023** [comment]
> I don't have a linux environment. The donate link in 0.3.0.2 now should be placed in the bottom of dock window. Can you check the version again?

Now I ensure that it works good....thank you so much...see picture.
![Screenshot from 2023-04-29 22-00-50](https://user-images.githubusercontent.com/131931769/235306876-af6d365c-4f0a-40b2-9bfe-846366dcf57e.png)

**Comment by sorayuki** [comment]
...... it may need some fix to match the new larger theme of OBS
________________________________
