### ISSUE TITLE
How do I build this addon in Nobara 37 (Gnome Fedora 37)?

### ISSUE THREAD

**Issue by Ryu945** [sorayuki/obs-multi-rtmp#287]
I am trying to build this addon for Nobara 37 (Gnome Fedora 37).  How do I compile it?  I know the the instructions are laid out by Ryu945 in the OBS Studio Discord room over their conversation chat history in the Linux support room but I do not have access to read that.

Does anyone know how to compile this addon for Nobara 37 (Gnome Fedora 37) or could someone read through that chat history and post what was mentioned here.  I meant to post what was in that conversation anyway so I could update the read me in this github repository.

**Comment by Ryu945** [comment]
https://github.com/sorayuki/obs-multi-rtmp/issues/220

I found this thread and installed the dependencies listed but the build command gives me an error about trying to install an apt-get program.  This is Fedora.  It shouldn't be using apt-get at all.

**Comment by AntonioGomes42** [comment]
Try creating a VM with Ubuntu and building the plugin, after that you use the compiled plugin to your fedora, it works as i show in this video 👉: https://youtu.be/p4eoEoq438M

**Comment by Ryu945** [comment]
> Try creating a VM with Ubuntu and building the plugin, after that you use the compiled plugin on your Fedora OS. It works for every kind of linux, as i show in this video point_right: https://youtu.be/p4eoEoq438M

I was going to try to install the software to build the old version that I could build on Fedora.  Then use that build script to try to build the updated one.   Right now,  I am trying to figure out how to build the old one.  libobs is giving me problems right now.

**Comment by Ryu945** [comment]
I tried building the latest addon in a Debian environment via Linux Mint.  Apparently Mint does have the correct versions of software to be able to build this addon.

**Comment by Ryu945** [comment]
I ended up uses Boxes to make an Ubuntu virtual machine.  Boxes already has ISOs of many OSes ready to go.  From their I downloaded the repository and built the addon with no problems using the script in the gitlab folder.  I then placed the addon based on the video linked in this thread.

https://youtu.be/p4eoEoq438M

**Comment by Mundo-Dev0ps** [comment]
@AntonioGomes42 works! Thank you! ✨
