### ISSUE TITLE
オーディオエンコーダーの種類がOBSから取得のみになりました

### ISSUE THREAD

**Issue by sumside** [sorayuki/obs-multi-rtmp#289]
OBS Sutadio ver 29.1
obs-multi-rtmp 0.3.0.2
上記にて確認。

オーディオエンコードの項目にて、「OBSから取得する」以外のエンコーダーが表示されなくなりました。

CoreAudioAAC、ならびにOBS標準になった新しいFFMPEG AACは使用できる状態です。

以上、報告でした。

![soray001](https://user-images.githubusercontent.com/39935284/235819064-29bf26f4-f903-43b9-8850-209e6b1eb077.png)

**Comment by sorayuki** [comment]
バ`ジョン29は今日リリ`スですね。何かの互Q性は菠欷靠赡苄预扦埂￥趣且ます。
________________________________
From: sumside ***@***.***>
Sent: Wednesday, May 3, 2023 9:46:31 AM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] オ`ディオエンコ`ダ`のNがOBSから取得のみになりました (Issue #289)


OBS Sutadio ver 29.1
obs-multi-rtmp 0.3.0.2
上にて_J。

オ`ディオエンコ`ドの目にて、「OBSから取得する」以外のエンコ`ダ`が表示されなくなりました。

CoreAudioAAC、ならびにOBS胜摔胜盲啃陇筏FFMPEG AACは使用できる状Bです。

以上、蟾妞扦筏俊

[soray001]<https://user-images.githubusercontent.com/39935284/235819064-29bf26f4-f903-43b9-8850-209e6b1eb077.png>

―

**Comment by sumside** [comment]
OBS29.1.1対応版、テストを行いました。
エンコーダーに各種コーデックが表示されるようになりました。
また、本日リリースされたOBS29.1.2でも表示がされることを確認できております。
まだ実際に配信してのテストは行っていませんが、時間が取れたら行う予定です。

お忙しいところ、ご対応ありがとうございました！

![shot_230529_130649](https://github.com/sorayuki/obs-multi-rtmp/assets/39935284/836134ad-ed2f-4539-b0ce-68016738fb84)

**Comment by sorayuki** [comment]
@sumside スクリーンショットでRTMPのキーは露出しましたから削除いただきます。

**Comment by sumside** [comment]
ありがとうございます。
RTMPキーはダミーですので大丈夫ですよ。
