### ISSUE TITLE
给不同目标推不同画面的音频问题

### ISSUE THREAD

**Issue by YJ233** [sorayuki/obs-multi-rtmp#292]
给不同目标推不同画面时如何分别设置不同的音频？
假设多路推流插件选择 场景a 的画面，当obs切换到 场景b 时，场景a 的音频会显示未激活没有声音，使用全局音频又会导致不同推流目标有相同的音频。有没有什么方式为不同目标不同画面分别设置不同的音频？

**Comment by sorayuki** [comment]
使用不同的audio mixer
________________________________
From: YJ233 ***@***.***>
Sent: Wednesday, May 17, 2023 4:57:01 AM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] 给不同目标推不同画面的音频问题 (Issue #292)


给不同目标推不同画面时如何分别设置不同的音频？
假设多路推流插件选择 场景a 的画面，当obs切换到 场景b 时，场景a 的音频会显示未激活没有声音，使用全局音频又会导致不同推流目标有相同的音频。有没有什么方式为不同目标不同画面分别设置不同的音频？

―

**Comment by YJ233** [comment]
<img width="503" alt="image" src="https://github.com/sorayuki/obs-multi-rtmp/assets/26440464/07879447-529f-4ec4-8cf0-cfdfc70fd659">

obs29.1.1声音设置的编码器只有“与obs一致”这一个选项

**Comment by sorayuki** [comment]
29.1的问题我还没时间去看。这两周找房子租、搬家、和原来房东周旋讨押金、把签了但是后悔的合租转出去，没多余的脑子了。一周或者两周才能静下来看
________________________________

**Comment by sorayuki** [comment]
论坛上也有好多人说29.1下有问题
________________________________

**Comment by YJ233** [comment]
了解，祝一切顺利

**Comment by sorayuki** [comment]
29.0.2是测过的，要不先用用29.0.2？
________________________________

**Comment by sorayuki** [comment]
29.1.1修了
