### ISSUE TITLE
在多个推流的不同场景中 只会推出正在激活的场景 其他场景黑屏

### ISSUE THREAD

**Issue by gufeiyue0** [sorayuki/obs-multi-rtmp#293]

**Comment by sorayuki** [comment]
你是不是加的媒体源然后没选有个不显示时停止播放还是什么的选项…？
________________________________
From: gufeiyue0 ***@***.***>
Sent: Tuesday, May 30, 2023 6:40:46 PM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] 在多个推流的不同场景中 只会推出正在激活的场景 其他场景黑屏 (Issue #293)


―

**Comment by gufeiyue0** [comment]
酸Q啊 搞定啦

**Comment by gufeiyue0** [comment]
> 

谢谢大哥

**Comment by cjdgyyy** [comment]
> 酸Q啊 搞定啦

如何搞定的呀 我现在也是这样
