### ISSUE TITLE
How to install plugin in OBS Studio Portable from portableapps.com?

### ISSUE THREAD

**Issue by Patraskon** [sorayuki/obs-multi-rtmp#297]
I downloaded OBS Studio Portable from portableapps.com and I want to use the obs-multi-rtmp plugin to stream to multiple platforms at once. However, I am not sure how to install the plugin in the portable version of OBS. Do I need to copy the plugin files to a specific folder or run a setup program? Please help me with the installation process.

**Comment by sorayuki** [comment]
extract the zip archive to ``OBSPortable\App\obs-studio``
