### ISSUE TITLE
Where are the server keys and settings stored to? 

### ISSUE THREAD

**Issue by mpek** [sorayuki/obs-multi-rtmp#298]
Would like to be able to backup/restore quickly all streaming keys and custom encoder settings.

**Comment by mpek** [comment]
Great. Thank you. Is it possible to copy/paste the keys and settings to a different profile in the same obs? If yes, how?

**Comment by sorayuki** [comment]
copy the whole obs-multi-rtmp section from one profile's ini file and insert (or overwrite) into another profile's ini file.

**Comment by mpek** [comment]
Nice, very nice, found it!
