### ISSUE TITLE
[feat]: The OBS has been updated to version 29.1.3, and the plugin also needs to be updated

### ISSUE THREAD

**Issue by Nliver** [sorayuki/obs-multi-rtmp#302]
OBS has been updated to version 29.1.3, and the plugin also needs to be updated

**Comment by mpek** [comment]
Works just fine over here. What happens with Multi RTMP with OBS 29.1.3 on your machine?

**Comment by arinora1** [comment]
I am having the issue with the streams not saving. I have tried the modify name but its not saving.

**Comment by ShrimpSenpai** [comment]
I have same Issue, also I had two platforms saved and only YouTube one was saved after shutting down PC, even after I delete it. '-'

**Comment by mpek** [comment]
What do you mean by streams not saving? 
What I had is, when changes made to obs-multi-rtmp and OBS crashes/freezes/hangsup after these changes made in same session, any changes made could possibly not being saved. 
Recommendation: Do your changes, close OBS, and reopen OBS > changes saved.
Somehow changes made in obs-multi-rtmp are dependend to OBS itself.

**Comment by arinora1** [comment]
I open OBS and add a new target. Once I close OBS and reopen the target I previously added is no longer there and I need to add it again.

**Comment by ShrimpSenpai** [comment]
I even downgrade OBS to 29.1.1 reinstall plugin, added YT and KICK, save, reopen OBS modify Save, and day later after restarting PC all saved options are deleted...
