### ISSUE TITLE
[Feat] AV1 and multi FPS

### ISSUE THREAD

**Issue by bensam123** [sorayuki/obs-multi-rtmp#304]
Can we get support for AV1 and FPS in the encoding options for multistream? Love the plugin, just looking for that extra little bit.

**Comment by mpek** [comment]
Why don't you set that in OBS and go from there?

**Comment by bensam123** [comment]
All services don't use the same standards or have the same limitations, so the same settings don't work for all of them.

**Comment by bensam123** [comment]
Looks like we have multiple encoders now, but still no option for FPS. Could we please get a FPS option? Certain platforms don't support 60fps for instance, like FB unless you're partnered.

Thanks for adding encoder options.

**Comment by sorayuki** [comment]
AV1 is enabled since 0.5.0.0.
Different framerate for each output is currently unsupported. OBS's API obs_add_view2 says that it ignores the framerate in the parameter of video information.
