### ISSUE TITLE
[Feature Request] Separate Auto-Start and Auto-Stop

### ISSUE THREAD

**Issue by mabrowning** [sorayuki/obs-multi-rtmp#307]
I use OBS to manage a public livestream of an event that has a portion that we do not broadcast. However, there are closed circuit monitoring systems in the facility where the event occurs that I use this (excellent!) multi-rtmp output to broadcast to.
As such, when I stop the public livestream, I need to re-start the broadcast in the Multiple Output dock. It would be very convenient if we could enable auto-start (which we'd want!) and auto-stop (which we'd like to turn off) independently.

**Comment by CortexReaver** [comment]
I'd like to use "auto-stop" function for my own convenience, because right now I have to press "Stop" or to "Stop all" manually after I stop streaming on the OBS panel.
