### ISSUE TITLE
How do you uninstall this plugin

### ISSUE THREAD

**Issue by N6REJ** [sorayuki/obs-multi-rtmp#310]
OBS keeps saying this plugin is out of date and to either update or remove it.  I'd like to just remove it.  How?
This is on windows 11

**Comment by mpek** [comment]
If you don't find the files in the usual folder in program files, you should check:

C:\Users\YOURUSER\AppData\Roaming\obs-studio

Had this issue as well and found the issuing parts at thiat location.

**Comment by sorayuki** [comment]
or, run the installer again and it will ask you whether removing the plugin
