### ISSUE TITLE
Advanced encoder settings

### ISSUE THREAD

**Issue by dietahvr** [sorayuki/obs-multi-rtmp#316]
Can you add advanced encoder settings to the Plugin, like in the default OBS Output Settings.
And then like in another Issue requested the option to re-use custom encoders for other platforms.

We would gladly pay for these features.

![grafik](https://github.com/sorayuki/obs-multi-rtmp/assets/107934544/4aa503f5-9c8e-42a5-875f-fd798efe40b2)

**Comment by sorayuki** [comment]
It's added in 0.5.0.0
