### ISSUE TITLE
Encoder parameters are not being loaded since latest update

### ISSUE THREAD

**Issue by ImAciidz** [sorayuki/obs-multi-rtmp#319]
Since the latest plugin update, encoder parameters (bitrate, b-frames, keyframe interval) are not being loaded from the json file. They will save & show in the json file if you make changes, but as soon as OBS is restarted, the bitrate, keyint, and bframes are reset to their default values. Same also happens for audio encoder - the bitrate isn't loaded and is reset to default 128kbps.

Tested on a fresh profile on OBS 29.1.3, Windows 11.

**Comment by sorayuki** [comment]
It'a big change on configuration saving & loading made in 0.4. I'll check this later

**Comment by sorayuki** [comment]
Hi, it's because the numeric value in configuration is stored as signed integer and load as unsigned integer.
But I checked the type of value as integer so the checking is not passed.

It's now fixed in 0.4.0.3
