### ISSUE TITLE
Virustotal give positive result on latest release (0.4.0.3)

### ISSUE THREAD

**Issue by ghost** [sorayuki/obs-multi-rtmp#322]
Hi.
Unfortunately, when uploading this file:
https://github.com/sorayuki/obs-multi-rtmp/releases/download/0.4.0.3/obs-multi-rtmp-0.4.0.3-windows-x64-Installer.exe

 in version 0.4.0.3 to virus total, one gets 10 positive virus messages.
When just pasting the link, there are no positive results. Only if the file is uploaded.
See here:

https://www.virustotal.com/gui/file/4942954c27a4925b5fddd25a920ae5b0584cbfbe4c19eaa80271435278fc7d9b

Most likely a false positive, I guess.
This issue was reported on the OBS plugin page and is the top-comment at the time of this post.
Thank you.

**Comment by doqfgc** [comment]
Ran the raw plugin DLL through VirusTotal and got a 0/67 positivity rate.

Those 10 you see are likely to do with the NSIS installer that's used. Generally harmless, but if you're paranoid, use the zip release instead.

[1] https://www.virustotal.com/gui/file/524417e8401a00e4542f5ac8c7b98b20197190a56680ec09a95d06598eb03378

**Comment by sorayuki** [comment]
Installer created by NSIS tends to be reported as like it contains virus. But it doesn't.
