### ISSUE TITLE
沒有出現多串流視窗

### ISSUE THREAD

**Issue by tomyHHC** [sorayuki/obs-multi-rtmp#323]
剛剛下載 obs-multi-rtmp-0.4.0.3-macos-universal.pkg，已安裝OBS，卻沒出現視窗，請問該怎麼處理？

https://cdn.discordapp.com/attachments/969594135516422204/1143377053199118357/2023-08-22_10.51.44.png

**Comment by sorayuki** [comment]
macos系统我不是很熟悉诶。
先看一下日志文件logfile，有没有载入失败的报错。
再试试看切换到工作室模式studio mode，有说法这种模式下能看到一个小的视窗，拖放出来就能用了。

**Comment by LuckyEricYz** [comment]
但是在工作室模式下，只有第一次进入左上角会有一个小的视窗，如果第二次进入就没有啦

**Comment by LuckyEricYz** [comment]
> macos系统我不是很熟悉诶。 先看一下日志文件logfile，有没有载入失败的报错。 再试试看切换到工作室模式studio mode，有说法这种模式下能看到一个小的视窗，拖放出来就能用了。

但是在工作室模式下，只有第一次进入左上角会有一个小的视窗，如果第二次进入就没有啦

**Comment by tomyHHC** [comment]
有看到了 在工作室模式下 還要放大（隱藏成一排）

感謝各位！
