### ISSUE TITLE
 could not find any instance of Visual Studio.

### ISSUE THREAD

**Issue by wakakaming** [sorayuki/obs-multi-rtmp#324]
=>   Configuring OBS Studio...
    =>   Configuring OBS...
-- OBS:  Application Version: 29.0.2 - Build Number: 2
CMake Error at CMakeLists.txt:15 (project):
  Generator

    Visual Studio 17 2022

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
[31;1mNativeCommandExitException: [31;1mProgram "cmake.exe" ended with non-zero exit code: 1.[0m
Exception: D:\obs-multi-rtmp-master-0b810f23f7f3e0d7a86cece867edbb354e5f21a8\.github\scripts\Build-Windows.ps1:101
Line |
 101 |  Build
     |  ~~~~~
     | cmake -S . -B plugin_build_x64 -G Visual Studio 17 2022 -DCMAKE_SYSTEM_VERSION=10.0.20348.0
     | -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DQT_VERSION=6 -DENABLE_PLUGINS=OFF
     | -DENABLE_UI=OFF -DENABLE_SCRIPTING=OFF
     | -DCMAKE_INSTALL_PREFIX:PATH=D:\obs-build-dependencies\plugin-deps-2023-01-06-qt6-x64
     | -DCMAKE_PREFIX_PATH:PATH=D:\obs-build-dependencies\plugin-deps-2023-01-06-qt6-x64 exited with non-zero code 1.

**Comment by sorayuki** [comment]
could not find any instance of Visual Studio.
