### ISSUE TITLE
Please make it compatible whit OBS 29.1.3

### ISSUE THREAD

**Issue by NurySenpaiVT** [sorayuki/obs-multi-rtmp#325]
Please make it compatible whit OBS 29.1.3 because it is currently the most stable and recent version of OBS and i can´t upgrade my OBS in order not to lose the plugin

**Comment by sorayuki** [comment]
The 0.4 works on 29.1.3 on Windows. 
Was it broken on Linux or macOS?

**Comment by MoRpH3uSYT** [comment]
Doesn't work for Mac. Can select the dock but it is not visible or usable

**Comment by sorayuki** [comment]
I checked the OBS's Build action log for 29.1.3, it was build with deps 2023-4-12 and qt6 2023-4-12, the same as that the plugin built with.
The dock window may hide somewhere. You may try edit the obs's configuration file ```global.ini``` and delete the line ```geometry=``` in ```[BasicWindow]``` section, then launch OBS to see if the dock window appears.
Notice that you will lose the docks' layout.

**Comment by shinyzhu** [comment]
Another way is you can `Reset Docks` first. Then you could see the window.

I've found it by this way.

**Comment by VictorKruger** [comment]
Currently the Linux debian installer is placing the files at a global level. As of the current version the files are placed in /usr/share/obs/obs-plugins/obs-multi-rtmp/locale/ and /usr/lib/x86_64-linux-gnu/obs-plugins/.  With the files installed globally, this could allow other users with access to OBS to see the stream key of another user.  

The proper install path for linux users needs to be /home/<user>/.config/obs-studio/plugins/obs-multi-rtmp/bin/64bit/obs-multi-rtmp.so and /home/<user>/.config/obs-studio/plugins/obs-multi-rtmp/data/locale/*.ini which will then allow each user on a system to have their own configuration.

I was able to manually install the plug-in in the appropriate location and verified that it does work with caveats.  The biggest issue is once the dock is hidden, it will not show back up.  You would need to close obs, move the obs-multi-rtmp out of the plugins folder, start obs, reset docks, close obs, move back the folder and restart obs for the plugin to be shown again.  

The plugin can not be resized when undocked which makes it difficult to use.  When the plugin is docked, it will not refresh and become unresponsive when moved or resized. The plugin requires a restart of obs for the plugin to become responsive again.
