### ISSUE TITLE
Sync Start option keeps resetting?

### ISSUE THREAD

**Issue by CantDrawStuff** [sorayuki/obs-multi-rtmp#327]
Hi there...
I recently upgraded pc and moved everything to the new one...
After reinstalling OBS and then the plugin I noticed that now the "sync start with OBS" keeps resetting to unchecked every time I close OBS
in case it's need:
OBS 29.1.3 (64bit)
Windows 11 v22H2 (10 on older pc) build 22621.2134

**Comment by sorayuki** [comment]
Hi, can you provide the detail operation steps?
It didn't reproduce here.

**Comment by CantDrawStuff** [comment]
I dunno...

o I just start OBS
o go to "modify"
o "sync start" is unchecked
o activate it
o start the stream and it works
o end stream
o close OBS
o reopen OBS, "sync start" is off again

never had problems with it before moving to windows 11
I could always uninstall/reinstall the plugin I suppose? (how the hell do I remove it tho?)

**Comment by sorayuki** [comment]
It still didn't reproduce here.

To remove the plugin, run the installer again and it will ask you whether removing it.
If it doesn't work, delete the folder ```C:\ProgramData\obs-studio\plugins\obs-multi-rtmp``` manually.

**Comment by CantDrawStuff** [comment]
Uh, okay...
Now it seems to work properly

For some reason unistalling and reinstalling fixed the issue

Well, thanks :)
Hopefully it won't happen again...
