### ISSUE TITLE
Bug with settings window scaling

### ISSUE THREAD

**Issue by kilroy98** [sorayuki/obs-multi-rtmp#328]
![Screenshot_3](https://github.com/sorayuki/obs-multi-rtmp/assets/13346898/d9bed599-eac3-44a3-93df-eb37efae9739)
When you open window with rtmp settings still all normal, but after you change encoder, window scaling starts looks like broken.

![Screenshot_1](https://github.com/sorayuki/obs-multi-rtmp/assets/13346898/b52336a1-0de1-424f-ae23-c73bff2179cb)
![Screenshot_2](https://github.com/sorayuki/obs-multi-rtmp/assets/13346898/0576c0ff-c9ae-42aa-a16d-69aa56b56856)

Plugin version - 0.5.0.0

**Comment by sorayuki** [comment]
fixed in 0.5.0.1
