### ISSUE TITLE
[feature] More options in "streaming settings" window

### ISSUE THREAD

**Issue by CortexReaver** [sorayuki/obs-multi-rtmp#329]
Such as "Rate control" (CBR or VBR) and "Profile" so I can restream on multiple platforms with different settings, because 
 each platform have it's own requirements.

**Comment by sorayuki** [comment]
See 0.5.0.0 pre-release
________________________________
From: CortexReaver ***@***.***>
Sent: Friday, September 8, 2023 2:04:23 AM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] [feature] More options in "streaming settings" window (Issue #329)


Such as "Rate control" (CBR or VBR) and "Profile".

―
