### ISSUE TITLE
[Request] Make it work in SLOBS - Streamlabs obs

### ISSUE THREAD

**Issue by eaeniko** [sorayuki/obs-multi-rtmp#33]
Can it be possible to work in streamlabs obs?

**Comment by reustaquiojr** [comment]
SLOBS is "another" application... It have closed source code maintained by Streamlabs crew !

Unless their team uses this code ... Don't wait any other way!

**Comment by sorayuki** [comment]
it doesn't work in streamlabs obs and I can't spare energy to get it work on SLOBS.
by the way, streamlabs obs is open sourced. https://github.com/stream-labs/streamlabs-obs/
