### ISSUE TITLE
Stream Setting Window  is too high and cant scroll down to select "OK"

### ISSUE THREAD

**Issue by Ben19430** [sorayuki/obs-multi-rtmp#339]
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/131845301/ecb97e8f-56a8-4c16-b56a-f5b714cd2a38)
Working with OBS29.1.3 and WIN11
The setting window is too high and cant adjust the size ,also cant scroll down. 
And it is full of my desktop screen.
Cant select "OK"to save the settings

**Comment by sorayuki** [comment]
先用yami以外的主题，空间利用率会更高。后面我往这个地方加个滚动条看看
________________________________
From: Ben19430 ***@***.***>
Sent: Saturday, September 30, 2023 3:53:45 PM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] Stream Setting Window is too high and cant scroll down to select "OK" (Issue #339)


[image]<https://user-images.githubusercontent.com/131845301/271761373-ecb97e8f-56a8-4c16-b56a-f5b714cd2a38.png>
Working with OBS29.1.3 and WIN11
The setting window is too high and cant adjust the size ,also cant scroll down.
Cant select "OK"to save the settings

―

**Comment by sorayuki** [comment]
有滚动条了现在
