### ISSUE TITLE
Is it possible to implement a choise of fps?

### ISSUE THREAD

**Issue by redstyle82** [sorayuki/obs-multi-rtmp#340]
Hello Sorayuki and thanks for the great work! Is there a way to implement also a choise for the fps output of your plugin? I have to send 2 different rtmp streams from obs to 2 different locations one @60fps and one @25fps. The actual solution is to open 2 obs istances but its very uncomfortable cause if u change fps in the second istance then it will save it also in the primary obs and have to change it every single time. With your TOP plugin it will be perfect to choose also the fps and solve me (and also to others) a big problem.

Thanks a lot

**Comment by redstyle82** [comment]
I forget to say, if you create a language file for IT (italian) language i can edit it for you so you have also that language ready.

**Comment by sorayuki** [comment]
Hello, there is no feature inside OBS to offer two video output pin with different FPS, also no API to insert a node in the pipe between video renderer and encoder. So currently it's a trouble, and can be only implemented in a very tricky method.
________________________________

**Comment by sorayuki** [comment]
in OBS 30.0 it becomes possible. try the latest version of the plugin
