### ISSUE TITLE
Mac OS 上无法正确设置多个推流

### ISSUE THREAD

**Issue by AlianBlank** [sorayuki/obs-multi-rtmp#342]
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/1950044/32b5f2f2-b386-48c1-896e-1d8a1199948a)
没有找到推流码的设置的地方

**Comment by sorayuki** [comment]
流名称就是了。这是OBS自己提供的翻译文案…
________________________________
From: Blank ***@***.***>
Sent: Wednesday, October 18, 2023 11:34:10 PM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] Mac OS 上无法正确设置多个推流 (Issue #342)


[image]<https://user-images.githubusercontent.com/1950044/276311820-32b5f2f2-b386-48c1-896e-1d8a1199948a.png>
没有找到推流码的设置的地方

―

**Comment by AlianBlank** [comment]
我将下面的那个设置为BIliBili 的推流码的时候，告诉我推流失败。

**Comment by AlianBlank** [comment]
我将下面的那个设置为BIliBili 的推流码的时候，告诉我推流失败。
![Uploading image.png…]()

**Comment by AlianBlank** [comment]
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/1950044/95241e7c-623c-429e-b2f0-f29f91503511)

**Comment by AlianBlank** [comment]
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/1950044/b8bd805d-7966-491a-87fe-ae267d7c9725)

**Comment by sorayuki** [comment]
B站的推流码应该比这个长多了……你是不是贴了身份码进去，不是那个东西
________________________________

**Comment by AlianBlank** [comment]
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/1950044/607be553-1234-4555-9391-adcdf393ddaa)

**Comment by sorayuki** [comment]
那你还是刷新一下开播设置那个页面，看看是不是点开播之后5分钟内没推上流房间被关了，重开一下
________________________________

**Comment by AlianBlank** [comment]
我已经重试过，重刷 串流密钥和身份码 和重新开播。依旧不行

**Comment by sorayuki** [comment]
如果找得到的话到OBS配置文件目录里看看配置文件里写的推流码和你复制出来的是不是一个样。这个版本比上个版本，显示推流码那个按钮删掉了，暂时还没加回来
________________________________

**Comment by AlianBlank** [comment]
obs-multi-rtmp.json  文件内容

{"audio_configs":[],"targets":[{"id":"2954607350","name":"BiliBili","output-param":{"bind_ip":"default","drop_threshold_ms":700,"max_shutdown_time_sec":30,"pframe_drop_threshold_ms":900},"service-param":{"key":"?streamname=live_101356690_87061563&key=bfb4da3ace30dafa725fe2e2f578f4f4&schedule=rtmp&pflag=1","password":"","server":"rtmp://live-push.bilivideo.com/live-bvc/","use_auth":false,"username":""},"sync-start":true},{"id":"884893239","name":"斗鱼","output-param":{"bind_ip":"default","drop_threshold_ms":700,"max_shutdown_time_sec":30,"pframe_drop_threshold_ms":900},"service-param":{"key":"","server":"rtmp://sendtc3.douyu.com/live","use_auth":false},"sync-start":false}],"video_configs":[]}

**Comment by AlianBlank** [comment]
那现在是怎么弄才能正常推流呢？我是最新版本的OBS+插件

**Comment by sorayuki** [comment]
这个情况我一时也判断不出来……看上去都是好的。B站推流码填主程序里推是好的是吧。等下，是不是主程序填了B站推流码，插件也填了，两个一起推，然后就坏了
________________________________

**Comment by AlianBlank** [comment]
我主程序也填写了推流程序码的。但是不是哔站的。使用这个插件是不是不能使用主程序的推流方式？

**Comment by sorayuki** [comment]
按理来说不是的。两边是独立的
________________________________

**Comment by AlianBlank** [comment]
我如果将主程序的推流移除掉之后。就会提示无法推送
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/1950044/3521c3b3-faf8-4a2d-b7dc-e5c93df1c027)

**Comment by AlianBlank** [comment]
所以现在是插件问题。还是我配置异常呢？

**Comment by sorayuki** [comment]
这状况我无法判断…
________________________________

**Comment by AlianBlank** [comment]
需要我怎么配合呢？如何才能把程序正常的使用呢？

**Comment by sorayuki** [comment]
连接直播流失败是服务器拒绝了推流，通常是类似房间没开播，码填错，重复推流之类。但是现在这两个都不是，没地方下手。
看下日志是不是有两个往B站推的？
也可以设置里把自动同步关了再试试
________________________________

**Comment by uumom** [comment]
我刚刚下过来也没办法使用，用默认的推流是可以的，但是多路的配置了就是报错

**Comment by MooneyChu** [comment]
我也是遇到了和上面一样的问题，买的新电脑下载了最新版本的obs和插件，出现了无法多路推流的情况，错误提示和上面截图一模一样。默认推流是可以正常，多路推流插件就推不出去

**Comment by lyx2000** [comment]
回到obs 29.1.3 插件 0.3.0.2 是可以成功的 新版本确实有些问题

**Comment by lyx2000** [comment]
回到obs 29.1.3 插件 0.3.0.2 是可以成功的 新版本确实有些问题

**Comment by EUnderground** [comment]
太对了！并且终于找到问这个问题的组织了。上面提的问题确实存在，绞尽脑汁都解决不了。各位先驱前辈有意境解决的吗？真心求教！

**Comment by lyx2000** [comment]
用特定版本的obs和插件是可以解决，但后面我们也不用这个方案了，用阿里云直播，多路推流，本地多路还是不稳定。
https://www.aliyun.com/product/live

**Comment by EUnderground** [comment]
同时再补充一些详细信息，我用的是[OBS Studio 31.0.0]版本，插件使用的是[obs-multi-rtmp-0.6.0.1-macos-universal.pkg]。在YouTube使用过程中出现了两个情况。第一，在单路普通推流的时候，用系统默认的 YouTube-rtmps 推流是可以的，只用填推流码就可以正常推。但是使用自定义，就会显示无法连接服务器（与上面附图一致）；第二，安装多路推流的插件之后，使用多路推Facebook就正常，然后同时推自定义YouTube依然不行。因为多路没有“系统默认的 YouTube-rtmps ”设置。所以无解。也不知哪位大神有我同样经历，欢迎显形来就大家于水火之中！
