### ISSUE TITLE
Constantly Reconnecting

### ISSUE THREAD

**Issue by Sevyn13** [sorayuki/obs-multi-rtmp#348]
I have Twitch streaming set up like normal in OBS and I set up to stream to Kick in the multi plugin by putting in the URL and Stream key. When I tell the plugin to start the Kick stream it starts for one second then says reconnecting and does that over and over.

**Comment by Satont** [comment]
Same for me, does you fixed it in any way?

**Comment by Sevyn13** [comment]
Yes I figured it out. Kick only supports a max resolution of 1920x1080 I have an ultra wide monitor and was trying to stream at 2580x1080 which is too high. I had to change the resolution I stream to Kick down to 1920x804. What resolution are you trying to stream at?

**Comment by Satont** [comment]
> Yes I figured it out. Kick only supports a max resolution of 1920x1080 I have an ultra wide monitor and was trying to stream at 2580x1080 which is too high. I had to change the resolution I stream to Kick down to 1920x804. What resolution are you trying to stream at?

Oh yeah, i'm also trying to stream 2k resolution. :)

Thank you for your answer. Then you maybe can close that issue?

**Comment by Sevyn13** [comment]
Kick's max resolution is 1920x1080 if you are trying to stream a high resolution it will not work.

**Comment by Satont** [comment]
> Kick's max resolution is 1920x1080 if you are trying to stream a higher resolution it will not work.

Yep, thats works. Thank.
