### ISSUE TITLE
Can't click "ok" to modify my stream output because it goes off the bottom of my screen.

### ISSUE THREAD

**Issue by OpenAI3** [sorayuki/obs-multi-rtmp#352]
I use a 4k tv and have it scaled to 300%, the only way for me to modify my 2nd stream output is by lowering how much its scaled. 
![Screenshot (20)](https://github.com/sorayuki/obs-multi-rtmp/assets/112646904/9176aa3e-8bfe-4cf4-860f-d891d49bdf6b)

**Comment by sorayuki** [comment]
It comes with a scroll bar in 0.5.0.3
