### ISSUE TITLE
Latest release marked by virus total

### ISSUE THREAD

**Issue by demortes** [sorayuki/obs-multi-rtmp#356]
https://www.virustotal.com/gui/file/8e9d7856aa0ac4229147056de175dd4f18ebc28d44d75fe9f172dd1fb8a520b1

Might be worth finding out why, and clean it up. Maybe upgrade of dependencies? Etc

**Comment by demortes** [comment]
FYI chrome blocked the download automatically as well.

**Comment by sorayuki** [comment]
The release is automated build by GitHub Action and should be clean. NSIS likely triggers fake reporting.

**Comment by unusualevent** [comment]
Can you generate the package using something besides Nullsoft Scriptable Install System?

**Comment by sorayuki** [comment]
it requires labour rewriting the whole install script.
the zip archive is not reported
________________________________
