### ISSUE TITLE
"Show key" button is missing

### ISSUE THREAD

**Issue by kilroy98** [sorayuki/obs-multi-rtmp#361]
On 0.5.0.3 i not see this button in output settings.
![Screenshot_3](https://github.com/sorayuki/obs-multi-rtmp/assets/13346898/4d44c4d3-6880-479a-99a8-c38bbe7639ba)

**Comment by kilroy98** [comment]
On "obs-multi-rtmp 0.5.0.3 for OBS 30.0.0" is still not showing.

**Comment by sorayuki** [comment]
It didn't update version code, nothing changed except adapting new version
