### ISSUE TITLE
Allow Linux Building outside .deb distributions

### ISSUE THREAD

**Issue by jcfrosty** [sorayuki/obs-multi-rtmp#368]
the build script seems to require apt commands to function at all.  It would be nice if the system would check if the linux distribution is deb based and then leave the package requirements to the end user if the script cannot determine them because apt doesn't exist. A list of requirements in the README.md should be more than enough for users to translate requirements themselves.

**Comment by sorayuki** [comment]
the build script comes from latest official obs plugin template

**Comment by jcfrosty** [comment]
The new package works well for all distros. Closing.
