### ISSUE TITLE
symbol lookup error when using in Linux

### ISSUE THREAD

**Issue by jcfrosty** [sorayuki/obs-multi-rtmp#369]
obs: symbol lookup error: /usr//lib/obs-plugins/obs-multi-rtmp.so: undefined symbol: obs_frontend_add_dock_by_id

prevents OBS from even loading. affects OBS v29 and OBS v30 when using plugin 5.0.3-OBS30 and 5.0.4.

**Comment by jcfrosty** [comment]
it seems to come from this commit

https://github.com/sorayuki/obs-multi-rtmp/commit/ae6504fba3f1a893e148c5312e1063c29edb96ed

**Comment by sorayuki** [comment]
Are you using an OBS with version of 30?

**Comment by jcfrosty** [comment]
Yes, I'm using OBS30, but it seems the error occurs in both OBS30 and 29

**Comment by jcfrosty** [comment]
So I ran updates today and rebuilt OBS30 and now the plugin works. It's possible there is a different dependency besides OBS that's needed. Probably QT6 updates as OBS30 depends on QT6+.
