### ISSUE TITLE
''Failed to start output. It's possible that encoder doesn't start.''

### ISSUE THREAD

**Issue by Art3mis-Ghub** [sorayuki/obs-multi-rtmp#371]
Hi,

I have an issue with this tool, it will start a multistream without issue except it refuses to stream to Twitch, regardless of stream key. I've tried resetting the key, changing settings, everything and it just won't start.
Streaming to YouTube and Kick works without any issues whatsoever, it's Twitch that fails to start.

![Screenshot 2023-11-22 130049](https://github.com/sorayuki/obs-multi-rtmp/assets/1610588/48c8e799-e643-4ec2-953a-1beb263349b1)

**Comment by Art3mis-Ghub** [comment]
What do you mean completed? You didn't even reply.

**Comment by sorayuki** [comment]
url target is empty
________________________________

**Comment by artvandalay767** [comment]
what do you set the url to? I can't find anywhere on twitch except my stream key, and when I just put my channel address it doesn't connect

**Comment by sorayuki** [comment]
https://dev.twitch.tv/docs/video-broadcast/reference/#get-ingest-servers

The part before {stream_key} is the server url

________________________________
发件人: artvandalay767 ***@***.***>
发送时间: Friday, August 30, 2024 2:29:20 AM
收件人: sorayuki/obs-multi-rtmp ***@***.***>
抄送: 雷Q ***@***.***>; State change ***@***.***>
主题: Re: [sorayuki/obs-multi-rtmp] ''Failed to start output. It's possible that encoder doesn't start.'' (Issue #371)


what do you set the url to? I can't find anywhere on twitch except my stream key, and when I just put my channel address it doesn't connect

―
