### ISSUE TITLE
Would it be possible to provide it also in a compressed format?

### ISSUE THREAD

**Issue by msmafra** [sorayuki/obs-multi-rtmp#375]
Hello there!

Would it be possible to provide a compressed format (.zip, tar.gz or tar.bz2) for the Linux version instead of just a .deb?

It would make easier not just for users of other distributions not based on Debian/Ubuntu but also users of OBS Studio in Flatpak format and even for Portable version.
Usually debs or rpms come with a bit of different folder structure on the other hand uncompressing a .zip/.tar.gz/tar.bz2 generates a folder with the plugin name just containing the bin and data folders .

**Comment by sorayuki** [comment]
The 0.5.0.3 CI worked well but starting from 0.5.0.3-OBS30 the tar.xz is disappeared.
I merged commits from OBS plugin template repository. Maybe it's the reason.

**Comment by sorayuki** [comment]
https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.5.0.4-nolinuxpackage

**Comment by msmafra** [comment]
Oh! Thank you. Being in that format already helps a lot.
It won't work by just uncompressing, because of the directory/folder structure generated when uncompressed/extracted is:
```
obs-multi-rtmp-0.5.0.4-x86_64-linux-gnu
├── lib
│   └── x86_64-linux-gnu
│       └── obs-plugins
│           └── obs-multi-rtmp.so
└── share
    └── obs
        └── obs-plugins
            └── obs-multi-rtmp
                └── locale
                    ├── an-ES.ini
                    ├── ar-AR.ini
                    ├── ar-SA.ini
                    ├── az-AZ.ini
                    ├── ba-RU.ini
                    ├── be-BY.ini
                    ├── bem-ZM.ini
                    ├── bg-BG.ini
                    ├── bn-BD.ini
                    ├── ca-ES.ini
                    ├── cs-CZ.ini
                    ├── da-DK.ini
                    ├── de-DE.ini
                    ├── el-GR.ini
                    ├── en-GB.ini
                    ├── en-US.ini
                    ├── eo-UY.ini
                    ├── es-ES.ini
                    ├── et-EE.ini
                    ├── eu-ES.ini
                    ├── fa-IR.ini
                    ├── fi-FI.ini
                    ├── fil-PH.ini
                    ├── fr-FR.ini
                    ├── gd-GB.ini
                    ├── gl-ES.ini
                    ├── he-IL.ini
                    ├── hi-IN.ini
                    ├── hr-HR.ini
                    ├── hu-HU.ini
                    ├── hy-AM.ini
                    ├── id-ID.ini
                    ├── it-IT.ini
                    ├── ja-JP.ini
                    ├── kab-KAB.ini
                    ├── ka-GE.ini
                    ├── kmr-TR.ini
                    ├── ko-KR.ini
                    ├── lo-LA.ini
                    ├── lt-LT.ini
                    ├── lv-LV.ini
                    ├── mn-MN.ini
                    ├── ms-MY.ini
                    ├── nb-NO.ini
                    ├── nl-NL.ini
                    ├── nn-NO.ini
                    ├── oc-FR.ini
                    ├── pa-IN.ini
                    ├── pl-PL.ini
                    ├── pt-BR.ini
                    ├── pt-PT.ini
                    ├── ro-RO.ini
                    ├── ru-RU.ini
                    ├── si-LK.ini
                    ├── sk-SK.ini
                    ├── sl-SI.ini
                    ├── sq-AL.ini
                    ├── sr-CS.ini
                    ├── sr-SP.ini
                    ├── sv-SE.ini
                    ├── szl-PL.ini
                    ├── ta-IN.ini
                    ├── te-IN.ini
                    ├── th-TH.ini
                    ├── tl-PH.ini
                    ├── tr-TR.ini
                    ├── uk-UA.ini
                    ├── ur-PK.ini
                    ├── vi-VN.ini
                    ├── zh-CN.ini
                    └── zh-TW.ini
```

OBS flatpak, portable need this structure:

``` obs-multi-rtmp
├── bin
│   └── 64bit
│       └── obs-multi-rtmp.so
└── data
    └── locale
        ├── an-ES.ini
        ├── ar-AR.ini
        ├── ar-SA.ini
        ├── az-AZ.ini
        ├── ba-RU.ini
        ├── be-BY.ini
        ├── bem-ZM.ini
        ├── bg-BG.ini
        ├── bn-BD.ini
        ├── ca-ES.ini
        ├── cs-CZ.ini
        ├── da-DK.ini
        ├── de-DE.ini
        ├── el-GR.ini
        ├── en-GB.ini
        ├── en-US.ini
        ├── eo-UY.ini
        ├── es-ES.ini
        ├── et-EE.ini
        ├── eu-ES.ini
        ├── fa-IR.ini
        ├── fi-FI.ini
        ├── fil-PH.ini
        ├── fr-FR.ini
        ├── gd-GB.ini
        ├── gl-ES.ini
        ├── he-IL.ini
        ├── hi-IN.ini
        ├── hr-HR.ini
        ├── hu-HU.ini
        ├── hy-AM.ini
        ├── id-ID.ini
        ├── it-IT.ini
        ├── ja-JP.ini
        ├── kab-KAB.ini
        ├── ka-GE.ini
        ├── kmr-TR.ini
        ├── ko-KR.ini
        ├── lo-LA.ini
        ├── lt-LT.ini
        ├── lv-LV.ini
        ├── mn-MN.ini
        ├── ms-MY.ini
        ├── nb-NO.ini
        ├── nl-NL.ini
        ├── nn-NO.ini
        ├── oc-FR.ini
        ├── pa-IN.ini
        ├── pl-PL.ini
        ├── pt-BR.ini
        ├── pt-PT.ini
        ├── ro-RO.ini
        ├── ru-RU.ini
        ├── si-LK.ini
        ├── sk-SK.ini
        ├── sl-SI.ini
        ├── sq-AL.ini
        ├── sr-CS.ini
        ├── sr-SP.ini
        ├── sv-SE.ini
        ├── szl-PL.ini
        ├── ta-IN.ini
        ├── te-IN.ini
        ├── th-TH.ini
        ├── tl-PH.ini
        ├── tr-TR.ini
        ├── uk-UA.ini
        ├── ur-PK.ini
        ├── vi-VN.ini
        ├── zh-CN.ini
        └── zh-TW.ini
```

With my bash script, using tar, I can re-structure the folders and files and copy the entire folder to the plugins path manually:

```
#!/usr/bin/env bash

declare output_file

output_file="obs-multi-rtmp-0.5.0.4-x86_64-linux-gnu.tar.xz"

tar --extract --verbose --transform='s#lib/x86_64-linux-gnu/obs-plugins#obs-multi-rtmp/bin/64bit#' --transform='s#share/obs/obs-plugins/obs-multi-rtmp#obs-multi-rtmp/data#' --file="/tmp/${output_file}" --directory=/tmp/
```

So, after downloading the .tar.xz I issue:
```
bash ~/Projects/TESTE-OBS-RTMP.sh ./obs-multi-rtmp-0.5.0.4-x86_64-linux-gnu.tar.xz
```
After tar's extraction and "transformation" I copy it to the plugins folder.

I can adapt the script and make it available, so it will copy to the correct paths already (flatpak's, portable's etc), copying over obs-multi-rtmp folder.

**Comment by sorayuki** [comment]
I don't use linux in daily life, rather newbie to it. I inspected how flatpak doing folder mapping for half a night with no luck, failing to find where it should locate. I will try your solution later.
________________________________

**Comment by msmafra** [comment]
Hi!

If you're not familiar $HOME will always point to the current users home directory, like: /home/sorayuki. Folders and files with a dot "." before their names are hidden ones. 

Flatpak's, being a sandboxed packaging format, the folders are kind of strange structured. But OBS's plugins folder, for example is:
`$HOME/.var/app/com.obsproject.Studio/config/obs-studio/plugins`

Similar on Fedora, for example, and I imagine OpenSUSE, Arch and others, the plugins folder is located at:
$HOME/.config/obs-studio/plugins

For the portable version I don't recall. I only used it when I compile OBS beta versions to test new features. I check and post here a bit later.

**Comment by msmafra** [comment]
I tried compiling for Portable but I think it's not What I think or something is wrong. So I'll ignore the portable.

**Comment by sorayuki** [comment]
Hello, I have fixed the package for Linux.
Would you like to have a look?

https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.5.0.4-flatpak

**Comment by msmafra** [comment]
> Owner

Hello there. Thanks for taking the time.

I think doing that way will cause confusion, since flatpak is yet another packing system/format on linux (with sandboxing etc). I, after extracting it, got confused thinking the package was broken because it was generating an empty folder. But, it wasn't the case, it is just creating a hidden .var folder inside the obs-multi-rtmp-0.5.0.4-x86_64-linux-gnu-flatpak generated from obs-multi-rtmp-0.5.0.4-x86_64-linux-gnu-flatpak.tar.xz. Where it looks like:

![Captura de tela de 2023-12-02 09-27-35](https://github.com/sorayuki/obs-multi-rtmp/assets/1005457/0d7d1294-6f6a-425d-8010-849240dcc24b)
Normal view
![Captura de tela de 2023-12-02 09-27-55](https://github.com/sorayuki/obs-multi-rtmp/assets/1005457/216f5430-e8c8-40b4-913e-d84e1a3b002f)
Hidden files/folders view

To exemplify better:
```
 ❯ tree -a ~/Downloads/Apps-etc/obs-multi-rtmp-0.5.0.4-x86_64-linux-gnu-flatpak/
/home/marcelo/Downloads/Apps-etc/obs-multi-rtmp-0.5.0.4-x86_64-linux-gnu-flatpak/
└── .var
    └── app
        └── com.obsproject.Studio
            └── config
                └── obs-studio
                    └── plugins
                        └── obs-multi-rtmp
                            ├── bin
                            │   └── 64bit
                            │       └── obs-multi-rtmp.so
                            └── data
                                └── locale
-- hidden to reduce number of lines --

12 directories, 72 files
```

I imagine your intention was for it to extract directly to the user's _.var_ folder. I actually don't know if that kind of contextual information can be stored inside a tar file and probably my explanation of the flatpak path was a bit confusing. 

To make it simple, I would like to suggest to remove all that path ".var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-multi-rtmp" and keep just the _bin_ and _data_ folders so when the file is extracted it would be just something like:
```
obs-multi-rtmp-0.5.0.4-x86_64-linux-gnu-flatpak/
├── bin
│   └── 64bit
└── data
    └── locale
```

And after the extraction one would only copy the obs-mult-rtmp-flatpak folder or rename it and copy it to the plugins folder manually.

Plugins can be packaged as Flatpaks too so they can be installed via the flatpak utility (command line) and/or via the graphical package manager, but seems a bit complex to do, at least for me. Some plugins have their flatpak version already (there they are called Addons) https://flathub.org/apps/com.obsproject.Studio.

[Building your first Flatpak](https://docs.flatpak.org/en/latest/first-build.html#building-your-first-flatpak)

**Comment by sorayuki** [comment]
The ```.config``` is also a hidden folder in Linux.
I often meet user that don't know how to have it installed. I found no "general installer" runs across Linux distributions which I did for Windows.

**Comment by msmafra** [comment]
> The `.config` is also a hidden folder in Linux. I often meet user that don't know how to have it installed. I found no "general installer" runs across Linux distributions which I did for Windows.

Unfortunately is confusing on Linux and with these "new" formats: AppImage, Flatpak and Snaps makes it yet harder. Not taking into account the already diverse established ones like DEB, RPM and compressed like tar.bz2, tar.gz and tar.xz. And those some times have slightly different structures.

**Comment by msmafra** [comment]
> I updated the archive directory structure and install hints. I hope it's clear enough for general Linux users (not developers)
> 
> https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.5.0.4-flatpak

That is awesome. With those instructions will much easier for non-devs since they can just copy the path and paste into the Path bar of their file manger.

Thank you kindly.

**Comment by bStyler** [comment]
@msmafra can you please help me understand how to install the plugin in my own Ubuntu 22.4 LTS?
