### ISSUE TITLE
Macos not Work

### ISSUE THREAD

**Issue by nio74** [sorayuki/obs-multi-rtmp#379]
Hello In Macos arm not work

**Comment by sorayuki** [comment]
It's probably the problem that directory structure the script generated.
I'll have a look at it after dealing with the same problem in Linux

**Comment by nio74** [comment]
> obs searches `~/Library/Application\ Support/obs-studio/plugins`. but the installer installed to `/Library/Application\ Support/obs-studio/plugins`. so just make a symbolic link: `ln -s /Library/Application\ Support/obs-studio/plugins ~/Library/Application\ Support/obs-studio`

thanks now work
