### ISSUE TITLE
在OBS开启的时候，修改obs-multi-rtmp.json不会即时生效？

### ISSUE THREAD

**Issue by jipinhetundu** [sorayuki/obs-multi-rtmp#383]
如题，只有先关闭obs--修改json--重启obs才能将改动同步进插件。这是正常的吗？有没有什么指令可以强制插件从json中重新读取属性？

**Comment by sorayuki** [comment]
只有启动的时候读一次。不会重新加载
________________________________
From: jipinhetundu ***@***.***>
Sent: Tuesday, December 5, 2023 8:51:55 PM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] 在OBS开启的时候，修改obs-multi-rtmp.json不会即时生效？ (Issue #383)


如题，只有先关闭obs--修改json--重启obs才能将改动同步进插件。这是正常的吗？有没有什么指令可以强制插件从json中重新读取属性？

―
