### ISSUE TITLE
[Feature Request] SRT support

### ISSUE THREAD

**Issue by TheXev** [sorayuki/obs-multi-rtmp#386]
this plugin works really great for me, but I really wish it had SRT support.

**Comment by lucaspontoexe** [comment]
I've been looking at the source code for a while and found out that SRT output can easily be added. 
Currently, the plugin is hardcoded to use the RTMP output:
https://github.com/sorayuki/obs-multi-rtmp/blob/b17240988b948bf0256503ac40b70a9b22049449/src/push-widget.cpp#L530

There are other outputs to use, depending on the protocol: `rtmp_output` for RTMP, `ffmpeg_hls_muxer` for HLS, and `ffmpeg_mpegts_muxer` for SRT and RIST.

I need to get familiar with OBS' internal API to figure out how to select them automatically, but it seems easy:
https://github.com/obsproject/obs-studio/blob/66978c4d23e32d0f67ec5ac7246a8fea01bf4740/UI/window-basic-main-outputs.cpp#L270

**Comment by lucaspontoexe** [comment]
There is a function in `rtmp_custom` service that can return the protocol that should be used: https://github.com/obsproject/obs-studio/blob/66978c4d23e32d0f67ec5ac7246a8fea01bf4740/plugins/rtmp-services/rtmp-custom.c#L118

or, if needed, just use `strncmp` the stream URL to get the right output

**Comment by lucaspontoexe** [comment]
update: i think I did it!  👀 
I'm gonna make a PR soon
