### ISSUE TITLE
Does not pass Closed Captions from Plugin

### ISSUE THREAD

**Issue by thesunnymachine** [sorayuki/obs-multi-rtmp#388]
https://obsproject.com/forum/resources/closed-captioning-via-google-speech-recognition.833/

This plugin will only send captions when streaming from the main connection, any streams coming from the Multi-RMPT will not send Closed captions.

**Comment by Khuntza** [comment]
I'd also like to see this feature enabled now that Twitch is allowing multistreaming officially.

**Comment by Tenebrosful** [comment]
Same problem here ! Using https://ultimatecc.net/ and captions aren't pass to multi-stream but only to primary

**Comment by sorayuki** [comment]
https://github.com/obsproject/obs-studio/blob/6f3f7b4e5a561a02bc0c7cd37260cd7814fba1a9/UI/frontend-plugins/frontend-tools/captions.cpp#L233

It does put the closed captions to main streaming output instance. It can't be done unless with the help of tricks like procedure hooking or something.

**Comment by Tenebrosful** [comment]
That's actually pretty sad :/
