### ISSUE TITLE
can you please create a tutorial of obs-multi-rtmp dock?

### ISSUE THREAD

**Issue by nirvanaruns** [sorayuki/obs-multi-rtmp#405]
Hello, I wanted to ask if it is possible for you to make a tutorial on how to create a custom obs dock where you can add simple things like textbox, buttons, simple texts, etc.
I have tried to follow YouTube tutorial videos regarding this but I can't find anything to start from. My idea is to create a custom dock for OBS that allows me to manage text files located in X path on my computer in order to show a score bar for my fighting game streams. I have a couple of softwares that do this action but I would like to integrate it directly into OBS. (The fields that are managed are: player's nickname, player's team, player's country, player's twitter, player's current score. And as an exception, there is a button that is for exchanging places between the players who are competing).

Based on this, will it be possible for you to create a kind of tutorial on how to create a basic dock in order to compile it and make it work in OBS? Thank you in advance.

Note: I took this project as a reference since it is the most similar to what I want to achieve. Please consider my request :(

thanks again :)

**Comment by sorayuki** [comment]
I think it's better to have a look at OBS's plugin template repository.

Here https://github.com/obsproject/obs-plugintemplate
