### ISSUE TITLE
I don{t see the docks in obs!

### ISSUE THREAD

**Issue by Sergio3215** [sorayuki/obs-multi-rtmp#408]
This release fail because i cannot see the option for multi session of stream
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/48896025/eb889652-9958-4c1a-8cc8-96a3e7f5f224)

**Comment by lucaspontoexe** [comment]
Check if your OBS is updated. From the screenshot, it seems that you are using an old version

**Comment by Sergio3215** [comment]
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/48896025/88de7378-ffdd-4223-bab3-9e411e3a04c1)
It is my version on obs, maybe you are in the correct and i am using old version of obs

**Comment by Sergio3215** [comment]
Can you help me?

**Comment by lucaspontoexe** [comment]
There it is: the latest version of this plugin is made for OBS 30. Try updating to see if it appears. Just click Help > Check Updates

**Comment by Sergio3215** [comment]
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/48896025/845a662f-ba7c-437a-8673-842bc46d6a55)
Thanks for your help, my issue was resolve updating the obs
