### ISSUE TITLE
error: format not a string literal and no format arguments [-Werror=format-security]

### ISSUE THREAD

**Issue by demensdeum** [sorayuki/obs-multi-rtmp#411]
https://github.com/sorayuki/obs-multi-rtmp/blob/b73168f0c2ee658345deae7baacb56ef3661828b/src/push-widget.cpp#L540

trying to install with yay on Arch Linux, got this error:
`17: error: format not a string literal and no format arguments [-Werror=format-security]
  540 |             blog(LOG_DEBUG, GetOutputID(url));
`

**Comment by sorayuki** [comment]
you can comment it out. I'll fix it lately
________________________________
From: Ilia Prokhorov ***@***.***>
Sent: Friday, March 15, 2024 8:03:48 AM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] error: format not a string literal and no format arguments [-Werror=format-security] (Issue #411)


https://github.com/sorayuki/obs-multi-rtmp/blob/b73168f0c2ee658345deae7baacb56ef3661828b/src/push-widget.cpp#L540

trying to install with yay on Arch Linux, got this error:
17: error: format not a string literal and no format arguments [-Werror=format-security] 540 | blog(LOG_DEBUG, GetOutputID(url));

―
