### ISSUE TITLE
Rescaling options new obs 30.1

### ISSUE THREAD

**Issue by davemil** [sorayuki/obs-multi-rtmp#412]
Please add support for new feature OBS v30.1:
Added GPU rescaling options for streaming and recording outputs [derrod]

**Comment by sorayuki** [comment]
It's in the master branch and not released yet.

**Comment by kilroy98** [comment]
@sorayuki is this in the "release/30.1" branch or is it not what is needed?
https://github.com/obsproject/obs-studio/commit/0a8e00c478401119309c050de7b23111b1af3ae6
