### ISSUE TITLE
Have option for bitrate with 'Get From OBS' Option Enabled.

### ISSUE THREAD

**Issue by Chiro1314** [sorayuki/obs-multi-rtmp#417]
I know you are a dev and i actually cant comprehend what obstacles you get while building such stuff but the option to keep bitrate different in plugin with the same streaming encoder seems like a must. Aitum vertical plugin has already done that. Is there any way you can build that feature in? I feel as if this is more important in my opinion as its a freaking hassle to keep 2 encoders on for twitch and youtube. Twitch will never accept bitrate above 8kbps and youtube looks crap on 8kpbs and that too with the h.264 nvenc. Hope so you can build it in as someone else (Aitum) has already done it.

**Comment by sorayuki** [comment]
It's impossible when encoder instance is shared between main output and side output.

**Comment by Chiro1314** [comment]
dayum. cab you let me know the difference between the jim and the ffmpeg
mode? Also does the low latency mode interferes with ultra low latency
option on Youtube? If you can, can you please provide details about it and
make them permanent on the github page itself? Thanks for the reply.

**Comment by sorayuki** [comment]
For the nvidia encoder, the “jim-“ one is newer and call to nvidia video codec SDK directly, and the other is integrated via ffmpeg.
Personally the “jim-“ one is preferred when available.

The latency mode in encoding settings means how it will be handled locally (your computer), and the option on Youtube means how youtube handle it on its server.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Chiro1314 ***@***.***>
发送时间: Saturday, March 30, 2024 1:25:37 AM
收件人: sorayuki/obs-multi-rtmp ***@***.***>
抄送: 雷鳴 ***@***.***>; State change ***@***.***>
主题: Re: [sorayuki/obs-multi-rtmp] Have option for bitrate with 'Get From OBS' Option Enabled. (Issue #417)


dayum. cab you let me know the difference between the jim and the ffmpeg
mode? Also does the low latency mode interferes with ultra low latency
option on Youtube? If you can, can you please provide details about it and
make them permanent on the github page itself? Thanks for the reply.

**Comment by Chiro1314** [comment]
Oh i see. Well, again thank you for replying. Just wanted to say that
personally, I have observed that ffmpeg tends to make the encoder less
overloaded than that of jim. Is it just me having a placebo effect or can
it be that as jim takes directly from the nvidia SDK, would it cause
encoder lag as it's already doing too much work?

**Comment by sorayuki** [comment]
According to the source code
https://github.com/obsproject/obs-studio/blob/004253f29633b38e7b1d8e0598e3f91a2ed790a9/plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c#L680
The ffmpeg one doesn’t has the “OBS_ENCODER_CAP_PASS_TEXTURE” flag, the rendered video will copy back from GPU memory to CPU memory and copy forward from CPU memory to GPU memory for encoding, thus it comes with more overhead in theory.

发件人: ***@***.***>
发送时间: 2024年3月30日 13:03
收件人: ***@***.***>
抄送: ***@***.***>; State ***@***.***>
主题: Re: [sorayuki/obs-multi-rtmp] Have option for bitrate with 'Get From OBS' Option Enabled. (Issue #417)

Oh i see. Well, again thank you for replying. Just wanted to say that
personally, I have observed that ffmpeg tends to make the encoder less
overloaded than that of jim. Is it just me having a placebo effect or can
it be that as jim takes directly from the nvidia SDK, would it cause
encoder lag as it's already doing too much work?
