### ISSUE TITLE
multi-rtmp并没有显示多路推流窗口

### ISSUE THREAD

**Issue by Zhang-Jia-Qi** [sorayuki/obs-multi-rtmp#422]
windows10环境下安装了OBS30.0.0和obs-multi-rtmp插件6.0.0，但是安装完后打开OBS，没有显示任何窗口
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/65662006/26960ed2-9daf-49cc-a1e1-a27bb8b4279a)
![image](https://github.com/sorayuki/obs-multi-rtmp/assets/65662006/1e05ce3d-f955-43e6-98ef-fb987dbb783b)

**Comment by sorayuki** [comment]
看下查看菜单的停靠窗口里面有没有
________________________________
From: ZhangJiaqi ***@***.***>
Sent: Saturday, May 4, 2024 4:09:40 PM
To: sorayuki/obs-multi-rtmp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sorayuki/obs-multi-rtmp] multi-rtmp并没有显示多路推流窗口 (Issue #422)


windows10环境下安装了OBS30.0.0和obs-multi-rtmp插件6.0.0，但是安装完后打开OBS，没有显示任何窗口
image.png (view on web)<https://github.com/sorayuki/obs-multi-rtmp/assets/65662006/26960ed2-9daf-49cc-a1e1-a27bb8b4279a>
image.png (view on web)<https://github.com/sorayuki/obs-multi-rtmp/assets/65662006/1e05ce3d-f955-43e6-98ef-fb987dbb783b>

―

**Comment by Zhang-Jia-Qi** [comment]
好的找到了，谢谢您
