### ISSUE TITLE
Can't view multiple chats

### ISSUE THREAD

**Issue by JuniperLea** [sorayuki/obs-multi-rtmp#443]
I just got the plugin set up and tested and the stream itself seems to be working properly.  Only problem is the only chat I'm able to view is my primary one and other chats don't appear in the same or separate window.  Is there a way to view multiple chats at once or is that not supported?

**Comment by averynoir** [comment]
> I just got the plugin set up and tested and the stream itself seems to be working properly. Only problem is the only chat I'm able to view is my primary one and other chats don't appear in the same or separate window. Is there a way to view multiple chats at once or is that not supported?

This is a Multi RTMP plugin, not a chat plugin.

**Comment by JuniperLea** [comment]
Figured it out, apparently the solution is to use custom browser docks, pop out the additional chat window from additional streams, and add the chat window as an additional dock.
