### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by derikcesar** [sorayuki/obs-multi-rtmp#47]
Dude I love you, where do I donate to you !?
Dude I love you, where do I donate to you !?
Dude I love you, where do I donate to you !?

**Comment by derikcesar** [comment]
????

**Comment by sorayuki** [comment]
It seems that Chinese bank account is not supported by github sponser.

**Comment by derikcesar** [comment]
find an international donation site for you, and post a link here that I will donate!

**Comment by derikcesar** [comment]
ty
