### ISSUE TITLE
可以做个mac客户端obs的插件么~

### ISSUE THREAD

**Issue by problem1** [sorayuki/obs-multi-rtmp#5]
可以做个mac客户端obs的插件么~现在mac下多平台只能用wirecast，但还是希望mac下的obs支持

**Comment by sorayuki** [comment]
我没有苹果电脑，也不会做苹果开发，不会搞。

**Comment by problem1** [comment]
装个黑苹果呗～哈哈～希望有大神能和你一起开发一个～

**Comment by jat001** [comment]
ffmpeg 是神器，送你一条命令，只要推流到 `rtmp://127.0.0.1:11935`，就能同时本地录制和推流到 youtube 和 b站。因为是 copy 视频流，几乎没有任何资源占用。
`|` 是分隔符，`[]` 里的是参数，具体看官方文档。

`ffmpeg -listen 1 -i rtmp://127.0.0.1:11935 -c copy -f tee -map 0 "[onfail=ignore:f=segment:segment_time=3600:strftime=1]'/my/videos/folder/%Y-%m-%d_%H-%M-%S.mkv'|[f=fifo:fifo_format=flv:drop_pkts_on_overflow=1:attempt_recovery=1:recovery_wait_time=1:recover_any_error=1]rtmp://a.rtmp.youtube.com/live2/xxxx-xxxx-xxxx-xxxx|[f=fifo:fifo_format=flv:drop_pkts_on_overflow=1:attempt_recovery=1:recovery_wait_time=1:recover_any_error=1]'rtmp://txy.live-send.acg.tv/live-txy/?streamname=xxxx&key=xxxx'"`

**Comment by sorayuki** [comment]
……淦我突然才发现不是回我的是回楼主的（捶地）
解锁了。
