### ISSUE TITLE
Network adapter

### ISSUE THREAD

**Issue by DjGreeZ** [sorayuki/obs-multi-rtmp#50]
Please add the ability to select a network card through which the multistream will go. In my case, I am using several network cards and different Internet providers. I would like to choose which provider the multistream will go through.
Thanks in advance!

**Comment by LordDragonus** [comment]
You have to use routes for this. It's not a thing which a plugin can handle or should handle.
For Windows use something like `route.exe add x.x.x.x mask 255.255.255.255 y.y.y.y` where x is the target IP and y is your second router (gateway). If necessary, adjust the mask too.

**Comment by DjGreeZ** [comment]
Тем не менее, хотелось бы иметь хотя бы возможность - использовать тот же сетевой адаптер, который выбран в настройках OBS. Без ручного прописывания маршрутов. Просто выбрав это в настройках плагина.

**Comment by DjGreeZ** [comment]
Nevertheless, I would like to be able to at least use the same network adapter that is selected in the OBS settings. Without manual prescription of routes. By simply selecting this in the plugin settings.

**Comment by DjGreeZ** [comment]
I would be grateful for a complete command to set the route. In my OBS settings there is an adapter with IP 10.1.1.4 - this is the same subnet as the main Internet. Only the main one I have is 10 gb / s and has a metric of 1. On a 10 Gb / S network, the stream starts to lose frames, but not on 1 gb / s. Therefore, I put the stream in OBS through a 1 gb / s adapter. I would like to start a multistream through it too. I don't know much about the settings and I'm afraid to write something wrong in the routes.

**Comment by serossi** [comment]
First of, Wrong about you set routes. It IS Job of the Plugin.
You can Bind OBS to any Network card you want. So normaly you would have 2 Networkcards, 2 Gateways.
Secondary Gateway (default route) would be set metric to 9000 so its never in use - except a Application is bound to that Network adapter. 

You can do this with physical and VLANs the correct routing to internet 2 or whatever (or trafficshaping or limiting or whatever you wanna do) is done later on the gateway aka Firewall

Second: No you cannot and should not attempt to set manual routes for the Plugin. This doenst work.
Routes are IP Based, but streaming services uses a wide range of IPs behind a single DNS entry. Unless you know all their IP ranges (and willing to future updates) this is not an option

Now for unknown reasons, the plugin doesnt use OBS Network settings which would solve the Issue.
What i can tell is that it uses OBS exe to bound out to network, but doenst respect the bind.

so obs then binds to 2 network cards. binding one is for regular stream, binding 2 is for default.
not shure if thats even plugins fault or OBS.

this seems indeed more of an OBS issue and could probably affect all plugins that need network, it just never really surfaced as most other plugins may not need as much network there

**Comment by serossi** [comment]
let me add, if you dont need absolutly seperate the traffic then i would suggest to make a dynamic rule based routing on the firewall.

simply seperate the streaming traffic and route it to the secondary WAN interface. 
what you should not do is simply use 2 home routers and connect em to two interfaces. it will work (kinds) but overall thats a very limited setup 

instead put a routerbox in between and let it manage your internet connections. that way you can have it also as a failover for primary internet and vice versa
