### ISSUE TITLE
Change settings saved ?

### ISSUE THREAD

**Issue by Arthur-crbr** [sorayuki/obs-multi-rtmp#57]
Hello,

I'm creating a program to automatically set the stream key.
I know that settings are saved in global.ini but it seems to be crypted.
I've : 
[obs-multi-rtmp]
json=cWJqcwEAAA.........
How can i get a normal code ?
Thank you

**Comment by sorayuki** [comment]
Hi,
You can decode it via base64 then it becomes normal json string.
