### ISSUE TITLE
Dock layout not fixed!

### ISSUE THREAD

**Issue by joeleldho02** [sorayuki/obs-multi-rtmp#59]
The UI dock layout of the multi streaming plugin is not fixed. It always goes back to its default layout when restarting OBS. I would like to have the UI dock layout to be fixed (recall previous layout, if any), when the user has made a change in the layout.

**Comment by RockNRollGeek** [comment]
+1 to this. Plugin has always been mostly unusable for me because when obs loads it squeezes the dock off to the side and I have to unlock my UI and manually fix it every time. This is the only plugin I've ever had this issue with, and it's persistent even with new installs.

**Comment by sharpthedj** [comment]
my problem is OBS is not showing any of the new subwindow with plugin, even after restart of layout :(

**Comment by russr999** [comment]
Hi @sorayuki, will you be able to fix the dock issue? It still goes back to the left and does not remember where it was when closed or UI locked. I dock it into one of the other windows and I would like it to stay there when I close and reopen OBS. Thanks

**Comment by sorayuki** [comment]
try 0.2.7, it should been fixed in this version.

**Comment by russr999** [comment]
> try 0.2.7, it should been fixed in this version.

Thank You :-) That seems to have fixed it
