### ISSUE TITLE
Feature Request: Send single Sources/Scenes 

### ISSUE THREAD

**Issue by Fred-DTV** [sorayuki/obs-multi-rtmp#63]
Thanks a lot for your great plugin!

We are trying to create a multi-angle live stream and for that reason it would be amazing to be able to send specific scenes or sources to additional RTMP servers.

Could be realized with a checkbox which items to send (video and audio) per RTMP server

**Comment by tatunts** [comment]
Yes! That would be awesome, maybe combining those two plugins? https://github.com/exeldro/obs-source-record

Thanks!

**Comment by matiaspl** [comment]
Sending out a "clean feed" or AUX from OBS would be awesome. A big +1 for this feature. In addition to obs-source-record there's obs-ndi that allows sending out preview, you could get some inspiration from there @sorayuki.

**Comment by BenJamesAndo** [comment]
![image](https://user-images.githubusercontent.com/44917135/230804183-46f484bd-05b9-4d8b-bc43-2f9475278dd1.png)
It looks as though this feature has recently been implemented. I tested it and it seems to work great.
