### ISSUE TITLE
Fix PayPal Donate Button

### ISSUE THREAD

**Issue by MrTeeXD** [sorayuki/obs-multi-rtmp#65]
Hello, I tried to Donate to you becuz I fell in love with your Plugin. I found out that you are using a Sandboxed PayPal Donate Widget which means no one can log in to send a donation. Hope you see this :D

**Comment by sorayuki** [comment]
I'm not familiar with paypal's service.
I'll have a look during weekends.

**Comment by MrTeeXD** [comment]
Alrighty. I really want to send you a donation for creating the plugin

**Comment by sorayuki** [comment]
I copied the code from paypal website again. but they seem to be the same with previous one.

**Comment by MrTeeXD** [comment]
This is the error I got when attempting to sign into my PayPal. Notice how the URL Says sandbox (dot) paypal (dot) com
![nyhxldVKDC](https://user-images.githubusercontent.com/37266538/108066170-a78e5f00-7067-11eb-99a8-52ed9d2ca68b.jpg)

**Comment by sorayuki** [comment]
finally I use paypal.me instead ...

**Comment by sorayuki** [comment]
It seems I can receieve payment successfully.

**Comment by MrTeeXD** [comment]
Sent you a donation. Thank you for making this plugin :D
