### ISSUE TITLE
Dock position isn't remembered

### ISSUE THREAD

**Issue by sneakyjoeru** [sorayuki/obs-multi-rtmp#7]
When you stack dock to another place, upon OBS restart it gets back to default placement.

**Comment by sorayuki** [comment]
I tried my best but can't handle the behavior of OBS. Also I can't find example codes.
I can only make it remember the direction it docks to, but not include the position it floats.

**Comment by sneakyjoeru** [comment]
If you can make it save at least docked position and size - that would be great. 
I'd like to have it as a tab with my Restream channels dock.

**Comment by RockNRollGeek** [comment]
Can confirm this issue, and it's a major headache. This is the only dock/panel that can't remember it's location and size and then forces itself off to the right side of my screen where I can't see it every time OBS loads. Regarding Sorayuki's comment, I'm using it docked, and not floating, and it still can't remember it's location and size when reloading OBS, just shoves it off the right side of the screen and sizes it to thin to see or use.

**Comment by sorayuki** [comment]
To tell the truth I'm not familiar with GUI development.
I just debugged it making it work for me.
Currently I have no idea how the issue happens and how to prevent.
