### ISSUE TITLE
Feature Request: Add support for FLT streams

### ISSUE THREAD

**Issue by Apostolique** [sorayuki/obs-multi-rtmp#71]
<https://glimesh.tv/> launched last Tuesday (March 2) and it uses the FTL protocol instead of RTMP. OBS already supports streaming to it out of the box. Would it be possible to add support for FTL streams?

**Comment by tytan652** [comment]
FTL in OBS will be deprecated
https://github.com/obsproject/obs-studio/discussions/4021

**Comment by Mythotical** [comment]
They still haven't depreciated the FTL protocol in OBS and they have released many new versions since then. Glimesh is close to an RTMP protocol release but they are being slow about it.

**Comment by Mythotical** [comment]
https://build.glimesh.tv/t/rtmp-testing-information/528
