### ISSUE TITLE
【macOS OBS 26.1.2】 当多路推流时，建议插件界面每一路之间的间距调小；当鼠标移动到插件界面边缘时，建议显示可伸缩鼠标图标样式。

### ISSUE THREAD

**Issue by keenlovelife** [sorayuki/obs-multi-rtmp#76]
系统：maxOS 
OBS: OBS 26.1.2

开发建议：
1. 当多路推流时，建议插件界面每一路之间的间距调小；中间空着很多空间浪费掉了，没必要间隔那么大。
2. 当鼠标移动到插件界面边缘时，建议显示可伸缩鼠标图标样式；第一次装的时候，这个插件界面宽只有一点点，一度以为是在macOS上显示的bug，后来摸索一阵才发现可以再拉宽点儿，建议鼠标在边缘时，鼠标变成可拉伸的那种ico。

![同时推多个流时，界面表现情况](https://z3.ax1x.com/2021/03/24/6bXsOJ.png)

**Comment by sorayuki** [comment]
不会做。

**Comment by keenlovelife** [comment]
> 不会做。

好的吧 ...

**Comment by tatianamarques** [comment]
Hi, there!
I can't understand Chinese.

I downloaded the plugin, but I don't know how to install it. I saw a
tutorial on youtube that shows a folder with two folders data and plugins.
But the file I downloaded from you came only with the executable file of
the plugin.

Could you help me, please? 😊

Thanks.

Em qui, 25 de mar de 2021 03:52, 大刀和长剑 ***@***.***> escreveu:
