### ISSUE TITLE
Zip file of release 0.2.6 being flagged as a trojan virus on Windows 10

### ISSUE THREAD

**Issue by aalkz** [sorayuki/obs-multi-rtmp#77]
The latest release (`0.2.6`) is being flagged as a trojan for me when I download the zip file. Other reports of this were posted in the comments [of a guide I made explaining how to install this plugin](https://www.youtube.com/watch?v=OylhZ9B698Q&lc=UgzZHzlXYF9gpZ8w71p4AaABAg), so I checked and it happened to me as well. I'm sure it's a false positive, but I think it's still an issue in need of attention.

Name of the supposed trojan: `Trojan:Win32/Zpevdo.B`

![image](https://user-images.githubusercontent.com/6750582/112706462-e3d48c80-8e69-11eb-84c8-0e34f3485f4a.png)

![image](https://user-images.githubusercontent.com/6750582/112706456-dc14e800-8e69-11eb-8a68-4858873455b1.png)

**Comment by sorayuki** [comment]
I have update the release file. Is it still reported?

**Comment by 3d-illusions** [comment]
still showing a virus

**Comment by d4vinder** [comment]
Just spent the whole morning scanning the pc! 

![image](https://user-images.githubusercontent.com/30625034/112748159-f22dc000-8fb1-11eb-8ce5-05e372d39cc4.png)

**Comment by sorayuki** [comment]
I don't know why a full-automatically build installer is reported containing virus ......
Is it because it has codes to delete file for working as uninstaller?

**Comment by sorayuki** [comment]
The uninstalling function in the installer is now removed.
Is it still reported as virus there?

**Comment by d4vinder** [comment]
I re-downloaded it and scanned it for any viruses. No viruses found using MalwareBytes or windows Defender with an Offline scan. Good work.

**Comment by nimik** [comment]
Just download and zoneAlarm next gen antivirus reported Malware.

**Comment by Threk-00** [comment]
I'm also getting a Trojan alert from Windows Defender, but mine says it's Wacatac.B!ml 
![screenshot_20210328192730](https://user-images.githubusercontent.com/81540178/112774252-b1a86380-8ffe-11eb-98a3-683a7239d48d.png)

**Comment by d4vinder** [comment]
Any updates to this? @sorayuki

**Comment by sorayuki** [comment]
A fully automated build artifact from totally opened source does not contain virus.

**Comment by sorayuki** [comment]
I have submit the file to Microsoft, mark as incorrect detection. Waiting for reply

**Comment by d4vinder** [comment]
> I have submit the file to Microsoft, mark as incorrect detection. Waiting for reply

Thanks. Please post the reply of the reasoning for labelling the code as malware.

**Comment by sorayuki** [comment]
![QQ截图20210402230638](https://user-images.githubusercontent.com/16860691/113427687-16512d00-9408-11eb-977a-7809eb6174f7.jpg)
Microsoft says it removed the detection.

**Comment by argeas** [comment]
Trend Micro APEX ONE is reporting it as Trojan.MacOS.PythonBackdoor..ESS2
OSX 11.5.
<img width="407" alt="Screenshot 2021-10-07 at 14 07 36" src="https://user-images.githubusercontent.com/17768789/136372792-2f65779b-5283-4065-8f41-81cd97401cc7.png">
2
