### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by jowbly** [sorayuki/obs-multi-rtmp#92]
The plugin is not saving the outputs, when i close my OBS, my outputs got deleted

**Comment by mdhedman** [comment]
Same here.  I have multiple streams setup, and when exiting OBS, all the settings are lost.

**Comment by mdhedman** [comment]
I saw that, after adding a new target, I have to click the modify button and then the okay, and it'll save it to the config file.  It doesn't save on just adding the first one.

**Comment by pilot40** [comment]
> I saw that, after adding a new target, I have to click the modify button and then the okay, and it'll save it to the config file. It doesn't save on just adding the first one.

Many thanks! This is how the settings are saved!

**Comment by sorayuki** [comment]
fixed in 0.2.6.1
