### ISSUE TITLE
Not working when OBS folder is moved

### ISSUE THREAD

**Issue by Vinylwalk3r** [sorayuki/obs-multi-rtmp#93]
I use my OBS as a portable install thats being synced (and backed up) via Onedrive to other computers. 
`C:\Users\[USER]\OneDrive\obs-studio\`

Now here's the thing. If I move my OBS to the directory the installer is bent on installing it in, the plugin works. No problems yet. But now, I move OBS and the WORKING plugin to my Onedrive folder. Suddenly, it stops working. Completly. Could anybody explain why its directory locked to working in ONLY `C:\ProgramData\obs-studio` ?

And an even better question, anybody got any idea how to get this plugin working on portable installs?

**Comment by DachsbauTV** [comment]
Exact same problem here +1

**Comment by sorayuki** [comment]
Hi, 0.2.7.1 comes with portable version, which was published before it comes with an installer.
